#!/usr/bin/env bash
# scripts/gen_shared_constants.sh
# -------------------------------------------------------------
# Emits n6shared/_shared_constants.hexa from atlas/n6_core_constants.hexa.
#
# Stage A consolidation: the 18 verify_*.hexa files consume the generated
# file via `use "n6shared/_shared_constants"`; `flatten_imports` inlines it
# at preflight time. Running this generator with `--check` fails on drift
# (CI preflight; see .github/workflows/ci.yml).
#
# Why bash (not hexa): the hexa toolchain itself may be absent on a fresh
# checkout during pre-commit; bash-only keeps the generator clean-room.
#
# Usage:
#   scripts/gen_shared_constants.sh            # regenerate (idempotent)
#   scripts/gen_shared_constants.sh --check    # exit 1 on drift
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SSOT="$ROOT/atlas/n6_core_constants.hexa"
OUT="$ROOT/n6shared/_shared_constants.hexa"
MODE="${1:-}"

if [[ ! -f "$SSOT" ]]; then
    echo "[gen_shared_constants] ERROR: SSOT missing: $SSOT" >&2
    exit 2
fi

# Extract the block between the two sentinel comments.
body="$(awk '
    /=== SSOT BEGIN/ { inblk=1; next }
    /=== SSOT END/   { inblk=0; next }
    inblk            { print }
' "$SSOT" | sed 's/^pub //')"

if [[ -z "$body" ]]; then
    echo "[gen_shared_constants] ERROR: empty SSOT block in $SSOT" >&2
    exit 2
fi

generated="$(cat <<EOF
// AUTO-GENERATED by scripts/gen_shared_constants.sh from
// atlas/n6_core_constants.hexa — DO NOT EDIT BY HAND.
//
// Consumed by the 18 verify_*.hexa files via:
//     use "n6shared/_shared_constants"
// \`tool/flatten_imports.hexa\` inlines this file at preflight.
// CI drift-check: \`scripts/gen_shared_constants.sh --check\`.
//
// Stage A (proposals/dup_derivation_consolidation_phase2_2026_04_24.md).

$body
EOF
)"

mkdir -p "$(dirname "$OUT")"

if [[ "$MODE" == "--check" ]]; then
    if [[ ! -f "$OUT" ]]; then
        echo "[gen_shared_constants] FAIL: $OUT missing" >&2
        exit 1
    fi
    if ! diff -u "$OUT" <(printf '%s\n' "$generated") >/dev/null; then
        echo "[gen_shared_constants] FAIL: $OUT differs from regenerated content" >&2
        echo "                         run: scripts/gen_shared_constants.sh" >&2
        diff -u "$OUT" <(printf '%s\n' "$generated") >&2 || true
        exit 1
    fi
    echo "[gen_shared_constants] OK (no drift)"
    exit 0
fi

printf '%s\n' "$generated" > "$OUT"
echo "[gen_shared_constants] wrote $OUT"
