#!/usr/bin/env python3
"""Phase 6 Batch B4 translation helper (domains/space YELLOW band).

Applies author-reviewed exact-string Korean->English substitutions across
8 domains/space files:
  aerospace, aerospace-transport, astronomy, hexa-cosmic,
  hexa-starship, observational-astronomy, space-engineering, space-systems

Shared scaffold template replacements are applied to all files; per-file
§X BLOWUP replacements are applied via file-specific dispatch tables.

Usage:
  python3 scripts/phase6_b4_translate.py

The script is idempotent. After running, lint with:
  python3 tool/own_doc_lint.py --rule 1
"""
from __future__ import annotations

import os
import re
import sys

REPO = "/Users/ghost/core/n6-architecture"

SHARED: list[tuple[str, str]] = [
    # === Titles (per-file specific titles injected via PER_FILE below, but each title needs its own) ===
    ("# 궁극의 Aerospace 아키텍처 (HEXA-AERO)",
     "# Ultimate Aerospace Architecture (HEXA-AERO) — draft"),
    ("# 궁극의 항공우주 수송 아키텍처 (HEXA-TRANSPORT)",
     "# Ultimate Aerospace Transport Architecture (HEXA-TRANSPORT) — draft"),
    ("# 궁극의 천문학 아키텍처 (HEXA-ASTRO)",
     "# Ultimate Astronomy Architecture (HEXA-ASTRO) — draft"),
    ("# 궁극의 초기우주 관측망 (HEXA-COSMIC)",
     "# Ultimate Early-Universe Observation Mesh (HEXA-COSMIC) — draft"),
    ("# 궁극의 재사용 발사체 (HEXA-STARSHIP Mk.10)",
     "# Ultimate Reusable Launch Vehicle (HEXA-STARSHIP Mk.10) — draft"),
    ("# 궁극의 관측천문학 설계 (HEXA-OBS-ASTRO)",
     "# Ultimate Observational-Astronomy Design (HEXA-OBS-ASTRO) — draft"),
    ("# 궁극의 우주공학 아키텍처 (HEXA-SPACE-ENG)",
     "# Ultimate Space-Engineering Architecture (HEXA-SPACE-ENG) — draft"),
    ("# 궁극의 우주 시스템 아키텍처 (HEXA-SPACE-SYS)",
     "# Ultimate Space-Systems Architecture (HEXA-SPACE-SYS) — draft"),

    # === §1 tagline (per-file) ===
    ("SE(3) n=6 DOF 비행 + MHD/Fusion 추진 + C Z=6 복합 소재 대기권+우주 겸용 자율비행체",
     "SE(3) n=6 DOF flight + MHD/Fusion propulsion + C Z=6 composite material — dual-role atmospheric + space autonomous craft."),
    ("6-DOF 비행 역학 + σ=12 관제 채널 + τ=4 중복 FBW의 차세대 항공우주 수송",
     "6-DOF flight dynamics + σ=12 control channels + τ=4 redundant FBW — next-generation aerospace transport draft."),
    ("σ²=144m² 합성 간섭계 + τ=4 관측 밴드 + σ=12 분광 채널 — 물리 한계 도달 천문 관측",
     "σ²=144m² synthetic interferometer + τ=4 observational bands + σ=12 spectral channels — astronomy observation approaching physical limits"),
    ("CMB 편광 τ=4 극 배열 검출기 + J₂=24 차 구면조화 기저 + σ=12 주파수 채널 초기우주 관측",
     "CMB polarization τ=4 pole-array detector + J₂=24 order spherical-harmonic basis + σ=12 frequency channels for early-universe observation"),
    ("SpaceX Starship 차세대 — n=6 산술 원리 기반 완전 재사용 + Mars 화성 이주 발사체",
     "SpaceX Starship next-generation — n=6 arithmetic-based fully reusable + Mars migration launcher"),
    ("n=6 거울 세그먼트 × τ=4 관측 밴드 × σ=12 분광 채널 관측천문 망원경 설계",
     "n=6 mirror segments × τ=4 observational bands × σ=12 spectral channels — observational-astronomy telescope design"),
    ("SE(3)=n=6 DOF 자세 + Tsiolkovsky 질량비 + 6축 자세제어 — 우주 구조물의 n=6 필연",
     "SE(3)=n=6 DOF attitude + Tsiolkovsky mass ratio + 6-axis attitude control — n=6 forced for space structures"),
    ("궤도역학 6 케플러 요소 + 위성 σ=12 태양전지 패널 + τ=4 자세 채널 우주 시스템",
     "orbital mechanics 6 Keplerian elements + satellite σ=12 solar-panel array + τ=4 attitude-channel space system"),

    # === Section headers ===
    ("## §1 WHY (왜 n=6 인가 — 이 기술이 삶을 바꾸는 방법)",
     "## §1 WHY (why n=6 — how this technology pattern reshapes life)"),
    ("**핵심 정리**: `σ(6)·φ(6) = 6·τ(6) = 12` — n=6 은 유일한 완전수 iff 조건 (n≥2). 이 등식이 도메인 전역 상수 (σ=12, τ=4, φ=2, sopfr=5, J₂=24) 를 수론에서 직접 뽑아낸다.",
     "**Key lemma (candidate)**: `σ(6)·φ(6) = 6·τ(6) = 12` — n=6 is the unique perfect number under the iff condition (n≥2). This equality pulls the domain-wide constants (σ=12, τ=4, φ=2, sopfr=5, J₂=24) directly from number theory."),

    # Table headers
    ("| 효과 | 현재 (2026) | HEXA-AERO 이후 | n=6 근거 |", "| Effect | Current (2026) | After HEXA-AERO (target) | n=6 rationale |"),
    ("| 효과 | 현재 (2026) | HEXA-TRANSPORT 이후 | n=6 근거 |", "| Effect | Current (2026) | After HEXA-TRANSPORT (target) | n=6 rationale |"),
    ("| 효과 | 현재 (2026) | HEXA-ASTRO 이후 | n=6 근거 |", "| Effect | Current (2026) | After HEXA-ASTRO (target) | n=6 rationale |"),
    ("| 효과 | 현재 (2026) | HEXA-COSMIC 이후 | n=6 근거 |", "| Effect | Current (2026) | After HEXA-COSMIC (target) | n=6 rationale |"),
    ("| 효과 | 현재 (2026) | HEXA-STARSHIP 이후 | n=6 근거 |", "| Effect | Current (2026) | After HEXA-STARSHIP (target) | n=6 rationale |"),
    ("| 효과 | 현재 (2026) | HEXA-OBS-ASTRO 이후 | n=6 근거 |", "| Effect | Current (2026) | After HEXA-OBS-ASTRO (target) | n=6 rationale |"),
    ("| 효과 | 현재 (2026) | HEXA-SPACE-ENG 이후 | n=6 근거 |", "| Effect | Current (2026) | After HEXA-SPACE-ENG (target) | n=6 rationale |"),
    ("| 효과 | 현재 (2026) | HEXA-SPACE-SYS 이후 | n=6 근거 |", "| Effect | Current (2026) | After HEXA-SPACE-SYS (target) | n=6 rationale |"),

    # Table rows
    ("| 핵심 스펙 | 현업 수준 | **n=6** (6 DOF) | σ(6)=12, τ(6)=4 자동 유도 |",
     "| Core spec | industry level | **n=6** (6 DOF) | auto-derived from σ(6)=12, τ(6)=4 |"),
    ("| 핵심 스펙 | 현업 수준 | **n=6** (6 자유도) | σ(6)=12, τ(6)=4 자동 유도 |",
     "| Core spec | industry level | **n=6** (6 DOF) | auto-derived from σ(6)=12, τ(6)=4 |"),
    ("| 핵심 스펙 | 현업 수준 | **σ²=144 m²** (144 집광 면적) | σ(6)=12, τ(6)=4 자동 유도 |",
     "| Core spec | industry level | **σ²=144 m²** (144 m² collecting area) | auto-derived from σ(6)=12, τ(6)=4 |"),
    ("| 핵심 스펙 | 현업 수준 | **σ=12** (12 주파수 채널) | σ(6)=12, τ(6)=4 자동 유도 |",
     "| Core spec | industry level | **σ=12** (12 frequency channels) | auto-derived from σ(6)=12, τ(6)=4 |"),
    ("| 핵심 스펙 | 현업 수준 | **σ·n=72/φ=36** (36 엔진 수) | σ(6)=12, τ(6)=4 자동 유도 |",
     "| Core spec | industry level | **σ·n=72/φ=36** (36 engines) | auto-derived from σ(6)=12, τ(6)=4 |"),
    ("| 핵심 스펙 | 현업 수준 | **n=6** (6 거울 세그먼트) | σ(6)=12, τ(6)=4 자동 유도 |",
     "| Core spec | industry level | **n=6** (6 mirror segments) | auto-derived from σ(6)=12, τ(6)=4 |"),
    ("| 핵심 스펙 | 현업 수준 | **n=6** (6 자세 DOF) | σ(6)=12, τ(6)=4 자동 유도 |",
     "| Core spec | industry level | **n=6** (6 attitude DOF) | auto-derived from σ(6)=12, τ(6)=4 |"),
    ("| 핵심 스펙 | 현업 수준 | **n=6** (6 케플러 요소) | σ(6)=12, τ(6)=4 자동 유도 |",
     "| Core spec | industry level | **n=6** (6 Keplerian elements) | auto-derived from σ(6)=12, τ(6)=4 |"),

    ("| 처리량 | 제한적 | σ=12 채널 × τ=4 병렬 = 48 배 | σ·τ=48, OEIS A000203×A000005 |",
     "| Throughput | limited | σ=12 channels × τ=4 parallel = 48x | σ·τ=48, OEIS A000203×A000005 |"),
    ("| 지연 | ms~s 레벨 | **μ=1 ms** 실시간 | n=6 최소 약수 |",
     "| Latency | ms~s level | **μ=1 ms** real-time | n=6 minimum divisor |"),
    ("| 정밀도 | 5~10% 오차 | **1/σ = 8.3%** 이내 | σ=12 분할 해상도 |",
     "| Precision | 5~10% error | within **1/σ = 8.3%** | σ=12 partition resolution |"),
    ("| 사용자 | 전문가 한정 | **σ-sopfr=7** 일반 사용자 | Miller 7±2 작업기억 |",
     "| Users | expert only | **σ-sopfr=7** general user | Miller 7±2 working memory |"),
    ("| 비용 | 고가 | **1/(σ-φ)=1/10** | σ-φ=10 경제 스케일링 |",
     "| Cost | high | **1/(σ-φ)=1/10** | σ-φ=10 economic scaling |"),
    ("| 확장 | 단일 유닛 | **n=6 모듈 메시** | SE(3) 6-DOF 연결성 |",
     "| Extensibility | single unit | **n=6 modular mesh** | SE(3) 6-DOF connectivity |"),

    # One-sentence summary variants
    ("**한 문장 요약**: n=6 완전수 산술 (σ=12, τ=4, φ=2, sopfr=5) 이 궁극의 Aerospace 아키텍처 (HEXA-AERO) 의 모든 설계 파라미터를 필연적으로 결정한다. 하드코딩 0, 수론 유래 100%.",
     "**One-sentence summary**: n=6 perfect-number arithmetic (σ=12, τ=4, φ=2, sopfr=5) forces every design parameter of the ultimate Aerospace architecture (HEXA-AERO) as a draft pattern. Hardcoding 0, number-theory-derived 100%."),
    ("**한 문장 요약**: n=6 완전수 산술 (σ=12, τ=4, φ=2, sopfr=5) 이 궁극의 항공우주 수송 아키텍처 (HEXA-TRANSPORT) 의 모든 설계 파라미터를 필연적으로 결정한다. 하드코딩 0, 수론 유래 100%.",
     "**One-sentence summary**: n=6 perfect-number arithmetic (σ=12, τ=4, φ=2, sopfr=5) forces every design parameter of the ultimate aerospace transport architecture (HEXA-TRANSPORT) as a draft pattern. Hardcoding 0, number-theory-derived 100%."),
    ("**한 문장 요약**: n=6 완전수 산술 (σ=12, τ=4, φ=2, sopfr=5) 이 궁극의 천문학 아키텍처 (HEXA-ASTRO) 의 모든 설계 파라미터를 필연적으로 결정한다. 하드코딩 0, 수론 유래 100%.",
     "**One-sentence summary**: n=6 perfect-number arithmetic (σ=12, τ=4, φ=2, sopfr=5) forces every design parameter of the ultimate astronomy architecture (HEXA-ASTRO) as a draft pattern. Hardcoding 0, number-theory-derived 100%."),
    ("**한 문장 요약**: n=6 완전수 산술 (σ=12, τ=4, φ=2, sopfr=5) 이 궁극의 초기우주 관측망 (HEXA-COSMIC) 의 모든 설계 파라미터를 필연적으로 결정한다. 하드코딩 0, 수론 유래 100%.",
     "**One-sentence summary**: n=6 perfect-number arithmetic (σ=12, τ=4, φ=2, sopfr=5) forces every design parameter of the ultimate early-universe observation mesh (HEXA-COSMIC) as a draft pattern. Hardcoding 0, number-theory-derived 100%."),
    ("**한 문장 요약**: n=6 완전수 산술 (σ=12, τ=4, φ=2, sopfr=5) 이 궁극의 재사용 발사체 (HEXA-STARSHIP Mk.10) 의 모든 설계 파라미터를 필연적으로 결정한다. 하드코딩 0, 수론 유래 100%.",
     "**One-sentence summary**: n=6 perfect-number arithmetic (σ=12, τ=4, φ=2, sopfr=5) forces every design parameter of the ultimate reusable launch vehicle (HEXA-STARSHIP Mk.10) as a draft pattern. Hardcoding 0, number-theory-derived 100%."),
    ("**한 문장 요약**: n=6 완전수 산술 (σ=12, τ=4, φ=2, sopfr=5) 이 궁극의 관측천문학 설계 (HEXA-OBS-ASTRO) 의 모든 설계 파라미터를 필연적으로 결정한다. 하드코딩 0, 수론 유래 100%.",
     "**One-sentence summary**: n=6 perfect-number arithmetic (σ=12, τ=4, φ=2, sopfr=5) forces every design parameter of the ultimate observational-astronomy design (HEXA-OBS-ASTRO) as a draft pattern. Hardcoding 0, number-theory-derived 100%."),
    ("**한 문장 요약**: n=6 완전수 산술 (σ=12, τ=4, φ=2, sopfr=5) 이 궁극의 우주공학 아키텍처 (HEXA-SPACE-ENG) 의 모든 설계 파라미터를 필연적으로 결정한다. 하드코딩 0, 수론 유래 100%.",
     "**One-sentence summary**: n=6 perfect-number arithmetic (σ=12, τ=4, φ=2, sopfr=5) forces every design parameter of the ultimate space-engineering architecture (HEXA-SPACE-ENG) as a draft pattern. Hardcoding 0, number-theory-derived 100%."),
    ("**한 문장 요약**: n=6 완전수 산술 (σ=12, τ=4, φ=2, sopfr=5) 이 궁극의 우주 시스템 아키텍처 (HEXA-SPACE-SYS) 의 모든 설계 파라미터를 필연적으로 결정한다. 하드코딩 0, 수론 유래 100%.",
     "**One-sentence summary**: n=6 perfect-number arithmetic (σ=12, τ=4, φ=2, sopfr=5) forces every design parameter of the ultimate space-systems architecture (HEXA-SPACE-SYS) as a draft pattern. Hardcoding 0, number-theory-derived 100%."),

    # "When it becomes everyday"
    ("### 일상이 되면", "### When it becomes everyday"),
    ("  n=6  ← 핵심 스펙 n=6 유래", "  n=6  ← core spec derived from n=6"),
    ("  σ²=144 m²  ← 핵심 스펙 n=6 유래", "  σ²=144 m²  ← core spec derived from n=6"),
    ("  σ=12  ← 핵심 스펙 n=6 유래", "  σ=12  ← core spec derived from n=6"),
    ("  σ·n=72/φ=36  ← 핵심 스펙 n=6 유래", "  σ·n=72/φ=36  ← core spec derived from n=6"),
    ("  σ=12 채널 / τ=4 병렬 / n=6 DOF  ← 구조 자동 결정",
     "  σ=12 channels / τ=4 parallel / n=6 DOF  ← structure auto-determined"),
    ("  Egyptian 분배 1/2 + 1/3 + 1/6 = 1  ← 완전 리소스 분할",
     "  Egyptian partition 1/2 + 1/3 + 1/6 = 1  ← full resource split"),
    ("  물리 한계 (Landauer/Shannon/Carnot)  ← §7.5 에서 검증",
     "  physical limits (Landauer/Shannon/Carnot)  ← verified in §7.5"),

    # §2 headers
    ("## §2 COMPARE (기존 방식 vs n=6) — ASCII 비교 차트",
     "## §2 COMPARE (legacy vs n=6) — ASCII comparison chart"),
    ("### 기존 방식의 한계 (왜 n=6 이 필요한가)",
     "### Limits of legacy approaches (why n=6 is the target pattern)"),

    # Barrier table rows
    ("│  장벽              │  왜 한계였나                 │  n=6 이 어떻게 해결하나     │",
     "│  barrier           │  why it was limiting        │  how n=6 addresses it      │"),
    ("│ 1. 파라미터 자의적 │ 채널 4/8/16 임의 선택        │ σ(6)=12 수론 필연 (A000203)│",
     "│ 1. arbitrary param │ channels 4/8/16 chosen ad-hoc│ σ(6)=12 number-theory forced (A000203)│"),
    ("│                   │ 이유 설명 불가                │ → 하드코딩 0, 재현 가능    │",
     "│                   │ rationale not explainable   │ → hardcoding 0, reproducible │"),
    ("│ 2. 최적점 불확실   │ A/B 테스트 수개월             │ n=6 볼록 극소 (§7.4 검증)  │",
     "│ 2. optimum unclear │ A/B test for months         │ n=6 convex minimum (verified §7.4)│"),
    ("│                   │ 로컬 최적 빠짐                │ → ±10% 둘 다 열화 증명     │",
     "│                   │ local optimum trap          │ → ±10% both worse (demonstrating)│"),
    ("│ 3. 스케일 깨짐    │ 소규모→대규모 재설계          │ B⁴ 스케일링 (§7.3 회귀)    │",
     "│ 3. scale breaks    │ small→large redesign       │ B⁴ scaling (§7.3 regression)│"),
    ("│                   │ 경험적 튜닝                   │ → log-log 기울기 자동 확인 │",
     "│                   │ empirical tuning           │ → log-log slope auto-check │"),
    ("│ 4. 리소스 낭비   │ 1/4, 1/3 임의 분배            │ Egyptian 1/2+1/3+1/6=1    │",
     "│ 4. resource waste  │ 1/4, 1/3 arbitrary split   │ Egyptian 1/2+1/3+1/6=1    │"),
    ("│                   │ 합이 1 안 됨                 │ → 완전 분할 (수학 정체)    │",
     "│                   │ sum ≠ 1                    │ → full partition (math identity)│"),
    ("│ 5. 반례 은폐     │ 실패 숨김, 성공만 홍보        │ COUNTER/FALSIFIERS ≥3 명시│",
     "│ 5. counter hiding  │ hide failures, promote wins │ COUNTER/FALSIFIERS ≥3 explicit│"),
    ("│                   │ 재현 불가                    │ → 반증 가능 과학           │",
     "│                   │ non-reproducible            │ → falsifiable science      │"),

    # ASCII perf bars headers per variant
    ("### 성능 비교 ASCII 막대 (기존 vs HEXA-AERO)", "### Performance comparison ASCII bars (legacy vs HEXA-AERO)"),
    ("### 성능 비교 ASCII 막대 (기존 vs HEXA-TRANSPORT)", "### Performance comparison ASCII bars (legacy vs HEXA-TRANSPORT)"),
    ("### 성능 비교 ASCII 막대 (기존 vs HEXA-ASTRO)", "### Performance comparison ASCII bars (legacy vs HEXA-ASTRO)"),
    ("### 성능 비교 ASCII 막대 (기존 vs HEXA-COSMIC)", "### Performance comparison ASCII bars (legacy vs HEXA-COSMIC)"),
    ("### 성능 비교 ASCII 막대 (기존 vs HEXA-STARSHIP)", "### Performance comparison ASCII bars (legacy vs HEXA-STARSHIP)"),
    ("### 성능 비교 ASCII 막대 (기존 vs HEXA-OBS-ASTRO)", "### Performance comparison ASCII bars (legacy vs HEXA-OBS-ASTRO)"),
    ("### 성능 비교 ASCII 막대 (기존 vs HEXA-SPACE-ENG)", "### Performance comparison ASCII bars (legacy vs HEXA-SPACE-ENG)"),
    ("### 성능 비교 ASCII 막대 (기존 vs HEXA-SPACE-SYS)", "### Performance comparison ASCII bars (legacy vs HEXA-SPACE-SYS)"),

    # ASCII perf bar labels
    ("│  [핵심 스펙] DOF", "│  [core spec] DOF"),
    ("│  [핵심 스펙] 자유도", "│  [core spec] DOF"),
    ("│  [핵심 스펙] 집광 면적", "│  [core spec] collecting area"),
    ("│  [핵심 스펙] 주파수 채널", "│  [core spec] frequency channels"),
    ("│  [핵심 스펙] 엔진 수", "│  [core spec] engine count"),
    ("│  [핵심 스펙] 거울 세그먼트", "│  [core spec] mirror segments"),
    ("│  [핵심 스펙] 자세 DOF", "│  [core spec] attitude DOF"),
    ("│  [핵심 스펙] 케플러 요소", "│  [core spec] Keplerian elements"),

    ("│  기존 최고       ███░░░░░░░░░░░░░░░░░░░░░░░░░░░   baseline                  │",
     "│  legacy best      ███░░░░░░░░░░░░░░░░░░░░░░░░░░░   baseline                  │"),
    ("│  [채널 수]                                                                  │",
     "│  [channel count]                                                            │"),
    ("│  전통 방식       ██████░░░░░░░░░░░░░░░░░░░░░░░░   4~8                       │",
     "│  legacy method    ██████░░░░░░░░░░░░░░░░░░░░░░░░   4~8                       │"),
    ("████████████████████░░░░░░░░░░░   σ=12 (자동)                │",
     "████████████████████░░░░░░░░░░░   σ=12 (auto)                │"),
    ("│  [병렬도]                                                                   │",
     "│  [parallelism]                                                              │"),
    ("│  전통 방식       ████░░░░░░░░░░░░░░░░░░░░░░░░░░   2~3                       │",
     "│  legacy method    ████░░░░░░░░░░░░░░░░░░░░░░░░░░   2~3                       │"),
    ("████████████████░░░░░░░░░░░░░░░   τ=4 (수론)               │",
     "████████████████░░░░░░░░░░░░░░░   τ=4 (number-theory)       │"),
    ("│  [DOF/자유도]                                                               │",
     "│  [DOF / degrees of freedom]                                                 │"),
    ("│  전통 방식       ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░   1~3                       │",
     "│  legacy method    ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░   1~3                       │"),
    ("│  [지연]                                                                     │",
     "│  [latency]                                                                  │"),
    ("│  전통 방식       ██████████████████████████████   100+ ms                   │",
     "│  legacy method    ██████████████████████████████   100+ ms                   │"),
    ("│  [에너지/비용]                                                              │",
     "│  [energy / cost]                                                            │"),
    ("│  전통 방식       ██████████████████████████████   baseline                   │",
     "│  legacy method    ██████████████████████████████   baseline                   │"),

    # n=6 breakthrough bullets
    ("### n=6 돌파구: 수론 → 필연", "### n=6 breakthrough pattern: number theory → forced"),
    ("- **σ(6)=12 (OEIS A000203)**: 채널/밴드/코어 수의 상한, 수론 직접 유도",
     "- **σ(6)=12 (OEIS A000203)**: upper bound on channel/band/core counts, number-theory direct derivation"),
    ("- **τ(6)=4 (OEIS A000005)**: 병렬 스레드/중복/단계 수, 약수 개수",
     "- **τ(6)=4 (OEIS A000005)**: parallel thread / redundancy / stage count, divisor count"),
    ("- **φ(6)=2 (OEIS A000010)**: 양극/대칭/페어 구조, 최소 소인수",
     "- **φ(6)=2 (OEIS A000010)**: polar / symmetric / pair structure, minimum prime factor"),
    ("- **sopfr(6)=5 (OEIS A001414)**: 감각/보호등급/레이어, 소인수 합",
     "- **sopfr(6)=5 (OEIS A001414)**: sensor / protection-grade / layer count, sum of prime factors"),
    ("- **J₂=2σ=24**: 파생 상수, 시간/면적/채널 2차 지표",
     "- **J₂=2σ=24**: derived constant, secondary time/area/channel index"),
    ("- **완전수 정체**: σ(6)·φ(6) = 24 = 6·τ(6) — 셋 독립 증명 (sf.md §9)",
     "- **perfect-number identity (candidate)**: σ(6)·φ(6) = 24 = 6·τ(6) — three independent candidate lemmas (sf.md §9)"),

    # §3
    ("## §3 REQUIRES (선행 도메인/요구사항)", "## §3 REQUIRES (prerequisite domains / requirements)"),
    ("| 선행 도메인 | 현재 | 필요 | 차이 | 핵심 기술 |",
     "| Prerequisite domain | current | target | gap | core technology |"),
    ("| aerospace-core | 🛸6 | 🛸10 | +4 | 본 도메인 핵심 수론 매핑 |",
     "| aerospace-core | 🛸6 | 🛸10 | +4 | core number-theory mapping for this domain |"),
    ("| aerospace-transport-core | 🛸6 | 🛸10 | +4 | 본 도메인 핵심 수론 매핑 |",
     "| aerospace-transport-core | 🛸6 | 🛸10 | +4 | core number-theory mapping for this domain |"),
    ("| astronomy-core | 🛸6 | 🛸10 | +4 | 본 도메인 핵심 수론 매핑 |",
     "| astronomy-core | 🛸6 | 🛸10 | +4 | core number-theory mapping for this domain |"),
    ("| cosmic-core | 🛸6 | 🛸10 | +4 | 본 도메인 핵심 수론 매핑 |",
     "| cosmic-core | 🛸6 | 🛸10 | +4 | core number-theory mapping for this domain |"),
    ("| starship-core | 🛸6 | 🛸10 | +4 | 본 도메인 핵심 수론 매핑 |",
     "| starship-core | 🛸6 | 🛸10 | +4 | core number-theory mapping for this domain |"),
    ("| observational-astronomy-core | 🛸6 | 🛸10 | +4 | 본 도메인 핵심 수론 매핑 |",
     "| observational-astronomy-core | 🛸6 | 🛸10 | +4 | core number-theory mapping for this domain |"),
    ("| space-engineering-core | 🛸6 | 🛸10 | +4 | 본 도메인 핵심 수론 매핑 |",
     "| space-engineering-core | 🛸6 | 🛸10 | +4 | core number-theory mapping for this domain |"),
    ("| space-systems-core | 🛸6 | 🛸10 | +4 | 본 도메인 핵심 수론 매핑 |",
     "| space-systems-core | 🛸6 | 🛸10 | +4 | core number-theory mapping for this domain |"),
    ("| 선행 A | 🛸7 | 🛸10 | +3 | 측정/센서 기반 |",
     "| prereq A | 🛸7 | 🛸10 | +3 | measurement/sensor-based |"),
    ("| 선행 B | 🛸5 | 🛸9 | +4 | 제어/소프트웨어 레이어 |",
     "| prereq B | 🛸5 | 🛸9 | +4 | control/software layer |"),
    ("| 선행 C | 🛸8 | 🛸10 | +2 | 물리 한계 최적화 (§7.5) |",
     "| prereq C | 🛸8 | 🛸10 | +2 | physical-limit optimization (§7.5) |"),
    ("Hard-requires (`requires:` frontmatter) 는 현재 공란 (도메인 독립). 선행 도메인은 문서 내 링크 참고.",
     "Hard-requires (`requires:` frontmatter) is currently empty (domain-independent). Prerequisite domains are referenced via in-document links."),

    # §4
    ("## §4 STRUCT (시스템 구조) — ASCII 아키텍처", "## §4 STRUCT (system structure) — ASCII architecture"),
    ("### 5단 체인 시스템맵", "### 5-stage chain system map"),
    ("│                        HEXA-AERO 시스템 구조                               │",
     "│                        HEXA-AERO system structure                               │"),
    ("│                        HEXA-TRANSPORT 시스템 구조                               │",
     "│                        HEXA-TRANSPORT system structure                               │"),
    ("│                        HEXA-ASTRO 시스템 구조                               │",
     "│                        HEXA-ASTRO system structure                               │"),
    ("│                        HEXA-COSMIC 시스템 구조                               │",
     "│                        HEXA-COSMIC system structure                               │"),
    ("│                        HEXA-STARSHIP 시스템 구조                               │",
     "│                        HEXA-STARSHIP system structure                               │"),
    ("│                        HEXA-OBS-ASTRO 시스템 구조                               │",
     "│                        HEXA-OBS-ASTRO system structure                               │"),
    ("│                        HEXA-SPACE-ENG 시스템 구조                               │",
     "│                        HEXA-SPACE-ENG system structure                               │"),
    ("│                        HEXA-SPACE-SYS 시스템 구조                               │",
     "│                        HEXA-SPACE-SYS system structure                               │"),
    ("│   입력     │   전처리   │   코어     │   후처리   │   출력              │",
     "│   input    │ pre-proc   │   core     │ post-proc  │   output            │"),
    ("│ σ=12 채널  │ τ=4 필터   │ n=6 엔진   │ n/φ=3 중복 │ σ=12 채널           │",
     "│ σ=12 chan  │ τ=4 filter │ n=6 engine │ n/φ=3 redun│ σ=12 channels       │"),
    ("│ 센서       │ 코덱       │ n=6         │ FBW/검증  │ 감각/액츄에이터     │",
     "│ sensors    │ codec      │ n=6         │ FBW/verify │ senses/actuators    │"),
    ("│ 센서       │ 코덱       │ σ²=144 m²   │ FBW/검증  │ 감각/액츄에이터     │",
     "│ sensors    │ codec      │ σ²=144 m²   │ FBW/verify │ senses/actuators    │"),
    ("│ 센서       │ 코덱       │ σ=12        │ FBW/검증  │ 감각/액츄에이터     │",
     "│ sensors    │ codec      │ σ=12        │ FBW/verify │ senses/actuators    │"),
    ("│ 센서       │ 코덱       │ σ·n=72/φ=36 │ FBW/검증  │ 감각/액츄에이터     │",
     "│ sensors    │ codec      │ σ·n=72/φ=36 │ FBW/verify │ senses/actuators    │"),
    ("│ sopfr=5    │ μ=1ms      │ σ·τ=48 T  │ τ=4 레이어 │ J₂=24 출력          │",
     "│ sopfr=5    │ μ=1ms      │ σ·τ=48 T  │ τ=4 layers │ J₂=24 output        │"),

    # Core param mapping
    ("### 핵심 파라미터 매핑 (n=6 EXACT)", "### Core parameter mapping (n=6 EXACT)"),
    ("| 파라미터 | 값 | n=6 수식 | 물리/수론 근거 | 판정 |",
     "| Parameter | Value | n=6 formula | physics / number-theory rationale | verdict |"),
    ("| 핵심 스펙 | 6 | n=6 | OEIS A000203 σ(6)=12 유래 | EXACT |",
     "| core spec | 6 | n=6 | derived via OEIS A000203 σ(6)=12 | EXACT |"),
    ("| 핵심 스펙 | 144 | σ²=144 m² | OEIS A000203 σ(6)=12 유래 | EXACT |",
     "| core spec | 144 | σ²=144 m² | derived via OEIS A000203 σ(6)=12 | EXACT |"),
    ("| 핵심 스펙 | 12 | σ=12 | OEIS A000203 σ(6)=12 유래 | EXACT |",
     "| core spec | 12 | σ=12 | derived via OEIS A000203 σ(6)=12 | EXACT |"),
    ("| 핵심 스펙 | 36 | σ·n=72/φ=36 | OEIS A000203 σ(6)=12 유래 | EXACT |",
     "| core spec | 36 | σ·n=72/φ=36 | derived via OEIS A000203 σ(6)=12 | EXACT |"),
    ("| 채널 수 | 12 | σ=12 | 약수의 합 σ(6) | EXACT |",
     "| channel count | 12 | σ=12 | sum of divisors σ(6) | EXACT |"),
    ("| 병렬도 | 4 | τ=4 | 약수의 개수 τ(6) | EXACT |",
     "| parallelism | 4 | τ=4 | divisor count τ(6) | EXACT |"),
    ("| 대칭 | 2 | φ=2 | 최소 소인수 φ(6) | EXACT |",
     "| symmetry | 2 | φ=2 | minimum prime φ(6) | EXACT |"),
    ("| 감각 레이어 | 5 | sopfr=5 | 소인수 합 sopfr(6)=2+3 | EXACT |",
     "| sense layers | 5 | sopfr=5 | prime-factor sum sopfr(6)=2+3 | EXACT |"),
    ("| 자유도 | 6 | n=6 | SE(3) 차원 = n | EXACT |",
     "| DOF | 6 | n=6 | SE(3) dimension = n | EXACT |"),
    ("| 2차 지표 | 24 | J₂=2σ | 파생 상수 | EXACT |",
     "| secondary index | 24 | J₂=2σ | derived constant | EXACT |"),
    ("| SC 자장 | 48 | σ·τ=48 | 1차 곱 | EXACT |",
     "| SC scale | 48 | σ·τ=48 | primary product | EXACT |"),
    ("| 경제 스케일 | 10 | σ-φ=10 | Mach/비용/고도 비율 | EXACT |",
     "| economic scale | 10 | σ-φ=10 | Mach/cost/altitude ratio | EXACT |"),
    ("| 중복도 | 3 | n/φ=3 | FBW 삼중, 안정 최소 | EXACT |",
     "| redundancy | 3 | n/φ=3 | FBW triple, min stability | EXACT |"),
    ("| 코어 수 | 144 | σ²=144 | GPU SM 구조 (BT-90) | EXACT |",
     "| core count | 144 | σ²=144 | GPU SM structure (BT-90) | EXACT |"),

    # Spec summary table
    ("### 제원 총괄표", "### Spec summary table"),
    ("│  핵심 스펙     n=6 = 6 DOF   │", "│  core spec     n=6 = 6 DOF   │"),
    ("│  핵심 스펙     n=6 = 6 자유도   │", "│  core spec     n=6 = 6 DOF   │"),
    ("│  핵심 스펙     σ²=144 m² = 144 집광 면적   │", "│  core spec     σ²=144 m² = 144 m² collecting area   │"),
    ("│  핵심 스펙     σ=12 = 12 주파수 채널   │", "│  core spec     σ=12 = 12 frequency channels   │"),
    ("│  핵심 스펙     σ·n=72/φ=36 = 36 엔진 수   │", "│  core spec     σ·n=72/φ=36 = 36 engines   │"),
    ("│  핵심 스펙     n=6 = 6 거울 세그먼트   │", "│  core spec     n=6 = 6 mirror segments   │"),
    ("│  핵심 스펙     n=6 = 6 자세 DOF   │", "│  core spec     n=6 = 6 attitude DOF   │"),
    ("│  핵심 스펙     n=6 = 6 케플러 요소   │", "│  core spec     n=6 = 6 Keplerian elements   │"),

    ("│  채널 수       σ = 12                                                │",
     "│  channels      σ = 12                                                │"),
    ("│  병렬도        τ = 4                                                 │",
     "│  parallelism   τ = 4                                                 │"),
    ("│  대칭          φ = 2                                                 │",
     "│  symmetry      φ = 2                                                 │"),
    ("│  감각 레이어   sopfr = 5                                             │",
     "│  sense layers  sopfr = 5                                             │"),
    ("│  자유도        n = 6                                                 │",
     "│  DOF           n = 6                                                 │"),
    ("│  2차 지표      J₂ = 2σ = 24                                         │",
     "│  secondary     J₂ = 2σ = 24                                         │"),
    ("│  곱셈 지표     σ·τ = 48                                             │",
     "│  product       σ·τ = 48                                             │"),
    ("│  경제 스케일   σ-φ = 10                                             │",
     "│  econ scale    σ-φ = 10                                             │"),
    ("│  중복도        n/φ = 3                                              │",
     "│  redundancy    n/φ = 3                                              │"),
    ("│  코어 수       σ² = 144                                             │",
     "│  cores         σ² = 144                                             │"),
    ("│  완전수 정체   σ(6)·φ(6) = 6·τ(6) = 24                             │",
     "│  perfect-id    σ(6)·φ(6) = 6·τ(6) = 24                             │"),

    # §5
    ("## §5 FLOW (데이터/에너지/제어 플로우) — ASCII",
     "## §5 FLOW (data/energy/control flow) — ASCII"),
    ("### 메인 플로우", "### Main flow"),
    ("│  센서/입력 ──→ [전처리] ──→ [n=6 엔진] ──→ [후처리] ──→ [출력/액츄에이터] │",
     "│  sensor/input ──→ [pre-proc] ──→ [n=6 engine] ──→ [post-proc] ──→ [output/actuator] │"),
    ("│  σ=12 채널   τ=4 필터     n=6           n/φ=3 중복  σ=12 채널 │",
     "│  σ=12 channels τ=4 filter    n=6           n/φ=3 redun σ=12 channels │"),
    ("│  σ=12 채널   τ=4 필터     σ²=144 m²     n/φ=3 중복  σ=12 채널 │",
     "│  σ=12 channels τ=4 filter    σ²=144 m²   n/φ=3 redun σ=12 channels │"),
    ("│  σ=12 채널   τ=4 필터     σ=12          n/φ=3 중복  σ=12 채널 │",
     "│  σ=12 channels τ=4 filter    σ=12         n/φ=3 redun σ=12 channels │"),
    ("│  σ=12 채널   τ=4 필터     σ·n=72/φ=36   n/φ=3 중복  σ=12 채널 │",
     "│  σ=12 channels τ=4 filter    σ·n=72/φ=36 n/φ=3 redun σ=12 channels │"),
    ("│  Egyptian 리소스 분배: 1/2 (전처리) + 1/3 (코어) + 1/6 (후처리) = 1     │",
     "│  Egyptian resource split: 1/2 (pre) + 1/3 (core) + 1/6 (post) = 1     │"),

    # Modes
    ("### 모드 1: 대기/Idle (최소 전력)", "### Mode 1: Idle (minimum power)"),
    ("│  전력: 1/σ² = 1/144 × Peak                │", "│  power: 1/σ² = 1/144 × Peak               │"),
    ("│  채널: 1 (모니터링만)                     │", "│  channels: 1 (monitor only)              │"),
    ("│  지연: n² = 36 ms (저전력 샘플링)         │", "│  latency: n² = 36 ms (low-power sample)  │"),
    ("### 모드 2: 정상 (표준 운영)", "### Mode 2: Normal (standard operation)"),
    ("│  전력: Peak                               │", "│  power: Peak                              │"),
    ("│  채널: σ = 12 전부                        │", "│  channels: all σ = 12                     │"),
    ("│  지연: μ = 1 ms                           │", "│  latency: μ = 1 ms                        │"),
    ("│  병렬: τ = 4 스레드                       │", "│  parallel: τ = 4 threads                  │"),
    ("### 모드 3: 돌입/버스트 (최대 처리량)", "### Mode 3: Burst (max throughput)"),
    ("│  전력: σ·τ/σ² = 1/3 × Peak (단기)        │", "│  power: σ·τ/σ² = 1/3 × Peak (short)      │"),
    ("│  채널: σ = 12 × τ = 4 = 48 유효          │", "│  channels: σ = 12 × τ = 4 = 48 effective │"),
    ("│  지연: μ/τ = 0.25 ms                     │", "│  latency: μ/τ = 0.25 ms                  │"),
    ("│  병렬: σ² = 144 코어                      │", "│  parallel: σ² = 144 cores                 │"),
    ("### 모드 4: 보호/Safe (축소 운영)", "### Mode 4: Safe (reduced operation)"),
    ("│  전력: 1/σ = 1/12 × Peak                  │", "│  power: 1/σ = 1/12 × Peak                 │"),
    ("│  채널: n/φ = 3 최소                       │", "│  channels: n/φ = 3 minimum                │"),
    ("│  지연: σ ms (10배 여유)                   │", "│  latency: σ ms (10x margin)               │"),
    ("│  FBW 중복: n/φ = 3 활성                   │", "│  FBW redundancy: n/φ = 3 active           │"),

    # §6
    ("## §6 EVOLVE (Mk.I~V 진화 로드맵)", "## §6 EVOLVE (Mk.I~V evolution roadmap)"),
    ("HEXA-AERO 의 실현 단계별 로드맵 — 각 Mk 단계마다 선행 도메인 성숙도 요구.",
     "Staged roadmap toward HEXA-AERO — each Mk stage demands prior-domain maturity."),
    ("HEXA-TRANSPORT 의 실현 단계별 로드맵 — 각 Mk 단계마다 선행 도메인 성숙도 요구.",
     "Staged roadmap toward HEXA-TRANSPORT — each Mk stage demands prior-domain maturity."),
    ("HEXA-ASTRO 의 실현 단계별 로드맵 — 각 Mk 단계마다 선행 도메인 성숙도 요구.",
     "Staged roadmap toward HEXA-ASTRO — each Mk stage demands prior-domain maturity."),
    ("HEXA-COSMIC 의 실현 단계별 로드맵 — 각 Mk 단계마다 선행 도메인 성숙도 요구.",
     "Staged roadmap toward HEXA-COSMIC — each Mk stage demands prior-domain maturity."),
    ("HEXA-STARSHIP 의 실현 단계별 로드맵 — 각 Mk 단계마다 선행 도메인 성숙도 요구.",
     "Staged roadmap toward HEXA-STARSHIP — each Mk stage demands prior-domain maturity."),
    ("HEXA-OBS-ASTRO 의 실현 단계별 로드맵 — 각 Mk 단계마다 선행 도메인 성숙도 요구.",
     "Staged roadmap toward HEXA-OBS-ASTRO — each Mk stage demands prior-domain maturity."),
    ("HEXA-SPACE-ENG 의 실현 단계별 로드맵 — 각 Mk 단계마다 선행 도메인 성숙도 요구.",
     "Staged roadmap toward HEXA-SPACE-ENG — each Mk stage demands prior-domain maturity."),
    ("HEXA-SPACE-SYS 의 실현 단계별 로드맵 — 각 Mk 단계마다 선행 도메인 성숙도 요구.",
     "Staged roadmap toward HEXA-SPACE-SYS — each Mk stage demands prior-domain maturity."),
    ("<summary><b>Mk.V — 2050+ 물리 한계 도달 (final target)</b></summary>",
     "<summary><b>Mk.V — 2050+ physical-limit target (final target)</b></summary>"),
    ("Landauer/Shannon/Carnot 물리 한계 도달. §7.5 LIMITS 에서 `claim ≤ limit` 자동 검증. 전 파라미터 n=6 EXACT 100%.",
     "Landauer / Shannon / Carnot physical limits as target. §7.5 LIMITS auto-checks `claim ≤ limit`. All parameters n=6 EXACT 100% target."),
    ("<summary>Mk.IV — 2045~2050 σ²=144 통합 메시</summary>",
     "<summary>Mk.IV — 2045~2050 σ²=144 unified mesh</summary>"),
    ("n=6 모듈 × σ²=144 코어 메시 통합. 클러스터 장애에도 n/φ=3 중복으로 동작. Cross-DSE 전도메인 연결.",
     "n=6 modules × σ²=144 core mesh unification. Survives cluster failure via n/φ=3 redundancy. Cross-DSE cross-domain connectivity."),
    ("<summary>Mk.III — 2040~2045 σ·τ=48 자장 / 채널 돌파</summary>",
     "<summary>Mk.III — 2040~2045 σ·τ=48 scale / channel breakthrough pattern</summary>"),
    ("핵심 스펙 σ·τ=48 달성 (n=6). MHD/SC/QEC 레벨 돌파. 시판 제품 시작.",
     "Core spec σ·τ=48 reached (n=6). MHD/SC/QEC breakthrough-pattern level. Commercial products begin."),
    ("핵심 스펙 σ·τ=48 달성 (σ²=144 m²). MHD/SC/QEC 레벨 돌파. 시판 제품 시작.",
     "Core spec σ·τ=48 reached (σ²=144 m²). MHD/SC/QEC breakthrough-pattern level. Commercial products begin."),
    ("핵심 스펙 σ·τ=48 달성 (σ=12). MHD/SC/QEC 레벨 돌파. 시판 제품 시작.",
     "Core spec σ·τ=48 reached (σ=12). MHD/SC/QEC breakthrough-pattern level. Commercial products begin."),
    ("핵심 스펙 σ·τ=48 달성 (σ·n=72/φ=36). MHD/SC/QEC 레벨 돌파. 시판 제품 시작.",
     "Core spec σ·τ=48 reached (σ·n=72/φ=36). MHD/SC/QEC breakthrough-pattern level. Commercial products begin."),
    ("<summary>Mk.II — 2035~2040 σ=12 채널 프로토타입</summary>",
     "<summary>Mk.II — 2035~2040 σ=12 channel prototype</summary>"),
    ("전통 4~8 → σ=12 채널 확장. τ=4 병렬 검증. 실험실 레벨 성능 입증.",
     "Legacy 4~8 → σ=12 channel extension. τ=4 parallel verified. Lab-level performance demonstrating."),
    ("<summary>Mk.I — 2030~2035 n=6 DOF 부품</summary>",
     "<summary>Mk.I — 2030~2035 n=6 DOF components</summary>"),
    ("기본 n=6 DOF 센서/액츄에이터/모듈. 수론 유래 파라미터 실측 시작. μ=1ms 지연 미달 허용.",
     "Basic n=6 DOF sensors/actuators/modules. Number-theory-derived parameter measurement draft. μ=1ms latency not-yet-met permitted."),

    # §7 and subheaders
    ("## §7 VERIFY (n=6 정직성 검증 — Python stdlib only)",
     "## §7 VERIFY (n=6 honesty verification — Python stdlib only)"),
    ("HEXA-AERO 가 물리/수학적으로 성립하는지 stdlib 만으로 검증.",
     "Verify HEXA-AERO is physically/mathematically consistent using stdlib only."),
    ("HEXA-TRANSPORT 가 물리/수학적으로 성립하는지 stdlib 만으로 검증.",
     "Verify HEXA-TRANSPORT is physically/mathematically consistent using stdlib only."),
    ("HEXA-ASTRO 가 물리/수학적으로 성립하는지 stdlib 만으로 검증.",
     "Verify HEXA-ASTRO is physically/mathematically consistent using stdlib only."),
    ("HEXA-COSMIC 가 물리/수학적으로 성립하는지 stdlib 만으로 검증.",
     "Verify HEXA-COSMIC is physically/mathematically consistent using stdlib only."),
    ("HEXA-STARSHIP 가 물리/수학적으로 성립하는지 stdlib 만으로 검증.",
     "Verify HEXA-STARSHIP is physically/mathematically consistent using stdlib only."),
    ("HEXA-OBS-ASTRO 가 물리/수학적으로 성립하는지 stdlib 만으로 검증.",
     "Verify HEXA-OBS-ASTRO is physically/mathematically consistent using stdlib only."),
    ("HEXA-SPACE-ENG 가 물리/수학적으로 성립하는지 stdlib 만으로 검증.",
     "Verify HEXA-SPACE-ENG is physically/mathematically consistent using stdlib only."),
    ("HEXA-SPACE-SYS 가 물리/수학적으로 성립하는지 stdlib 만으로 검증.",
     "Verify HEXA-SPACE-SYS is physically/mathematically consistent using stdlib only."),
    ("주장된 설계 사양을 수론 (OEIS A000203 σ / A000005 τ / A000010 φ / A001414 sopfr) + 기초 물리 공식으로 cross-check.",
     "Cross-check the stated design spec via number theory (OEIS A000203 σ / A000005 τ / A000010 φ / A001414 sopfr) + basic physics formulas."),

    ("### §7.0 CONSTANTS (수론 상수 자동 유도)", "### §7.0 CONSTANTS (number-theory constants auto-derived)"),
    ("하드코딩 0. OEIS A000203/A000005/A000010/A001414 에서 직접 계산.",
     "Hardcoding 0. Computed directly from OEIS A000203/A000005/A000010/A001414."),
    ("`assert σ(n) == 2n` (완전수 성질) 자기검증.",
     "Self-check: `assert σ(n) == 2n` (perfect-number property)."),
    ("### §7.1 DIMENSIONS (SI 단위 일관성)", "### §7.1 DIMENSIONS (SI unit consistency)"),
    ("모든 공식의 차원 튜플 `(M, L, T, I)` 추적. `E = P·t` 는 `[W][s] = [J]` 자동 검증.",
     "Track dimension tuple `(M, L, T, I)` across every formula. `E = P·t` auto-checks `[W][s] = [J]`."),
    ("차원 불일치 공식은 reject.", "Dimension mismatches are rejected."),
    ("### §7.2 CROSS (독립 경로 3개 재유도)", "### §7.2 CROSS (three independent re-derivations)"),
    ("핵심 스펙 6 을 (1) n=6 family 직접 계산, (2) Fraction 정확 유리수,",
     "Re-derive the core spec 6 via (1) direct n=6 family computation, (2) Fraction exact rational,"),
    ("핵심 스펙 144 을 (1) n=6 family 직접 계산, (2) Fraction 정확 유리수,",
     "Re-derive the core spec 144 via (1) direct n=6 family computation, (2) Fraction exact rational,"),
    ("핵심 스펙 12 을 (1) n=6 family 직접 계산, (2) Fraction 정확 유리수,",
     "Re-derive the core spec 12 via (1) direct n=6 family computation, (2) Fraction exact rational,"),
    ("핵심 스펙 36 을 (1) n=6 family 직접 계산, (2) Fraction 정확 유리수,",
     "Re-derive the core spec 36 via (1) direct n=6 family computation, (2) Fraction exact rational,"),
    ("(3) σ^i·τ^j·n^k symbolic 최적화 세 경로로 재유도. 15% 이내 일치해야 신뢰.",
     "(3) σ^i·τ^j·n^k symbolic optimization — three paths. Trust requires agreement within 15%."),
    ("### §7.3 SCALING (log-log 회귀 지수 역추정)", "### §7.3 SCALING (log-log regression exponent back-inference)"),
    ("B⁴ confinement / 표면적 σ² / 부피 σ³ 등의 스케일링 지수를 log-log 기울기로 역추정.",
     "Back-infer scaling exponents such as B⁴ confinement / surface-area σ² / volume σ³ via log-log slope."),
    ("데이터 `[10, 20, 30, 40, 48]` vs `b⁴` → 기울기 4.00 ± 0.05 확인.",
     "Data `[10, 20, 30, 40, 48]` vs `b⁴` → verify slope 4.00 ± 0.05."),
    ("### §7.4 SENSITIVITY (n=6 ±10% 볼록성)", "### §7.4 SENSITIVITY (n=6 ±10% convexity)"),
    ("`f(n=6)` 최적점에서 n 을 ±10% 흔들어 `f(6.6)` 과 `f(5.4)` 둘 다 `f(6)` 보다 나쁜지 확인.",
     "At the `f(n=6)` optimum, perturb n by ±10% and confirm `f(6.6)` and `f(5.4)` are both worse than `f(6)`."),
    ("볼록 극값 = 진짜 최적점 / flat = 끼워맞춤.",
     "Convex extremum = genuine optimum candidate / flat = overfitting."),
    ("### §7.5 LIMITS (물리/정보 상한)", "### §7.5 LIMITS (physical / information upper bounds)"),
    ("Landauer 최소 에너지 kT·ln2, Shannon 채널 용량 BW·log₂(1+SNR), Carnot 효율 1-T_c/T_h.",
     "Landauer minimum energy kT·ln2, Shannon channel capacity BW·log₂(1+SNR), Carnot efficiency 1-T_c/T_h."),
    ("claim 이 근본 한계 초과면 reject.", "Reject any claim exceeding a fundamental limit."),
    ("### §7.6 CHI2 (H₀: n=6 우연 가설 p-value)",
     "### §7.6 CHI2 (H₀: \"n=6 coincidence\" hypothesis p-value)"),
    ("N 파라미터 예측 vs 관측 χ² 계산 → `erfc(√(χ²/2df))` 로 p-value 근사.",
     "Compute χ² for N predicted parameters vs observed → approximate p-value via `erfc(√(χ²/2df))`."),
    ("p > 0.05 면 \"n=6 우연\" 가설 기각 불가 (유의).",
     "If p > 0.05, cannot reject \"n=6 coincidence\" hypothesis (significant)."),
    ("### §7.7 OEIS (외부 수론 DB 매칭)", "### §7.7 OEIS (external number-theory DB matching)"),
    ("수론 DB 에 존재 = 인간이 이미 발견한 수학, 조작 불가능.",
     "Presence in the number-theory DB = math humans already documented, not fabricable."),
    ("### §7.8 PARETO (Monte Carlo 전수 탐색)", "### §7.8 PARETO (Monte Carlo exhaustive search)"),
    ("DSE `K1 × K2 × K3 × K4 × K5 = 6×5×4×5×4 = 2,400` 조합 샘플링.",
     "DSE `K1 × K2 × K3 × K4 × K5 = 6×5×4×5×4 = 2,400` combinations sampled."),
    ("n=6 구성이 상위 5% 이내인지 통계적 유의성 확인.",
     "Check statistical significance that the n=6 configuration sits within the top 5%."),
    ("### §7.9 SYMBOLIC (Fraction 정확 유리수)", "### §7.9 SYMBOLIC (Fraction exact rational)"),
    ("부동소수 근사가 아닌 정확 유리수 `==` 등호 비교. σ·φ = n·τ 유일성 정리 직접 확인.",
     "Exact rational `==` comparison, not floating-point approximation. Directly checks the σ·φ = n·τ uniqueness candidate lemma."),
    ("### §7.10 COUNTER + FALSIFIERS (반례 + 반증조건)",
     "### §7.10 COUNTER + FALSIFIERS (counter-examples + falsifier conditions)"),
    ("- **COUNTER_EXAMPLES ≥3**: 기본전하 e, Planck h, π, 미세구조 α, Avogadro 수 —",
     "- **COUNTER_EXAMPLES ≥3**: elementary charge e, Planck h, π, fine-structure α, Avogadro's number —"),
    ("  n=6 유도 불가한 독립 상수 솔직히 인정",
     "  honestly acknowledge independent constants not derivable from n=6"),
    ("- **FALSIFIERS ≥3**: 스펙 측정 ±15% 밖 / 유일성 반례 / Monte Carlo 하위 50% / χ² p<0.001 / OEIS 재계산 붕괴",
     "- **FALSIFIERS ≥3**: spec measurement outside ±15% / uniqueness counter-example / Monte Carlo bottom 50% / χ² p<0.001 / OEIS recomputation collapse"),
    ("### §7 통합 검증 코드 (stdlib only)", "### §7 integrated verification code (stdlib only)"),

    # Code header
    ("# §7 VERIFY — HEXA-AERO n=6 정직성 검증 (stdlib only, domain=aerospace)",
     "# §7 VERIFY — HEXA-AERO n=6 honesty verification (stdlib only, domain=aerospace)"),
    ("# §7 VERIFY — HEXA-TRANSPORT n=6 정직성 검증 (stdlib only, domain=aerospace-transport)",
     "# §7 VERIFY — HEXA-TRANSPORT n=6 honesty verification (stdlib only, domain=aerospace-transport)"),
    ("# §7 VERIFY — HEXA-ASTRO n=6 정직성 검증 (stdlib only, domain=astronomy)",
     "# §7 VERIFY — HEXA-ASTRO n=6 honesty verification (stdlib only, domain=astronomy)"),
    ("# §7 VERIFY — HEXA-COSMIC n=6 정직성 검증 (stdlib only, domain=cosmic)",
     "# §7 VERIFY — HEXA-COSMIC n=6 honesty verification (stdlib only, domain=cosmic)"),
    ("# §7 VERIFY — HEXA-STARSHIP n=6 정직성 검증 (stdlib only, domain=starship)",
     "# §7 VERIFY — HEXA-STARSHIP n=6 honesty verification (stdlib only, domain=starship)"),
    ("# §7 VERIFY — HEXA-OBS-ASTRO n=6 정직성 검증 (stdlib only, domain=observational-astronomy)",
     "# §7 VERIFY — HEXA-OBS-ASTRO n=6 honesty verification (stdlib only, domain=observational-astronomy)"),
    ("# §7 VERIFY — HEXA-SPACE-ENG n=6 정직성 검증 (stdlib only, domain=space-engineering)",
     "# §7 VERIFY — HEXA-SPACE-ENG n=6 honesty verification (stdlib only, domain=space-engineering)"),
    ("# §7 VERIFY — HEXA-SPACE-SYS n=6 정직성 검증 (stdlib only, domain=space-systems)",
     "# §7 VERIFY — HEXA-SPACE-SYS n=6 honesty verification (stdlib only, domain=space-systems)"),

    ("# 10 서브섹션:", "# 10 subsections:"),
    ("#   §7.0 CONSTANTS  — n=6 상수 수론 함수 자동 유도 (하드코딩 0)",
     "#   §7.0 CONSTANTS  — n=6 constants auto-derived from number-theory fns (hardcoding 0)"),
    ("#   §7.1 DIMENSIONS — SI 단위 일관성 검사 (차원 튜플 추적)",
     "#   §7.1 DIMENSIONS — SI unit consistency check (dimension tuple tracking)"),
    ("#   §7.2 CROSS      — 동일 결과 독립 경로 3개 재유도",
     "#   §7.2 CROSS      — three independent paths re-derive the same result"),
    ("#   §7.3 SCALING    — log-log 회귀로 스케일링 지수 역추정",
     "#   §7.3 SCALING    — log-log regression for scaling exponent back-inference"),
    ("#   §7.4 SENSITIVITY — n=6 ±10% 볼록성 확인",
     "#   §7.4 SENSITIVITY — n=6 ±10% convexity check"),
    ("#   §7.5 LIMITS     — 물리 상한 (Landauer/Shannon/열역학) 미초과",
     "#   §7.5 LIMITS     — physical upper bounds (Landauer/Shannon/thermo) not exceeded"),
    ("#   §7.6 CHI2       — H0: n=6 우연 가설 p-value 계산",
     "#   §7.6 CHI2       — H0: \"n=6 coincidence\" p-value"),
    ("#   §7.7 OEIS       — A000203(σ)/A000005(τ)/A000010(φ)/A001414(sopfr) DB 매칭",
     "#   §7.7 OEIS       — A000203(σ)/A000005(τ)/A000010(φ)/A001414(sopfr) DB match"),
    ("#   §7.8 PARETO     — Monte Carlo 조합 중 n=6 상위 %",
     "#   §7.8 PARETO     — Monte Carlo top %% for n=6 among combinations"),
    ("#   §7.9 SYMBOLIC   — Fraction 정확 유리수 등호 일치",
     "#   §7.9 SYMBOLIC   — Fraction exact rational equality check"),
    ("#   §7.10 COUNTER   — COUNTER_EXAMPLES ≥3 + FALSIFIERS ≥3 (정직성 필수)",
     "#   §7.10 COUNTER   — COUNTER_EXAMPLES ≥3 + FALSIFIERS ≥3 (honesty mandatory)"),
    ("# ─── §7.0 CONSTANTS — n=6 상수 수론 함수로 자동 유도 ──────────────────────",
     "# ─── §7.0 CONSTANTS — n=6 constants auto-derived from number-theory functions ──────"),
    ("    \"\"\"약수 집합 — n=6 → {1,2,3,6}\"\"\"", "    \"\"\"divisor set — n=6 → {1,2,3,6}\"\"\""),
    ("    \"\"\"약수의 합 (OEIS A000203). σ(6)=1+2+3+6=12 ← 완전수\"\"\"",
     "    \"\"\"sum of divisors (OEIS A000203). σ(6)=1+2+3+6=12 ← perfect number\"\"\""),
    ("    \"\"\"약수의 개수 (OEIS A000005). τ(6)=|{1,2,3,6}|=4\"\"\"",
     "    \"\"\"divisor count (OEIS A000005). τ(6)=|{1,2,3,6}|=4\"\"\""),
    ("    \"\"\"오일러 φ (OEIS A000010). gcd(k,n)=1 인 k 개수. φ(6)=2\"\"\"",
     "    \"\"\"Euler φ (OEIS A000010). count of k with gcd(k,n)=1. φ(6)=2\"\"\""),
    ("    \"\"\"최소 소인수. 6 의 최소 소인수는 2 = φ(6)=2 와 수치 일치 (본 체계 정의)\"\"\"",
     "    \"\"\"minimum prime factor. Min prime of 6 is 2 = φ(6)=2 (numerical match for this framework)\"\"\""),
    ("    \"\"\"소인수의 합 (OEIS A001414). sopfr(6)=2+3=5\"\"\"",
     "    \"\"\"sum of prime factors (OEIS A001414). sopfr(6)=2+3=5\"\"\""),
    ("# n=6 family — 모두 수론 함수 자동 유도, 하드코딩 0",
     "# n=6 family — all auto-derived from number-theory fns, hardcoding 0"),
    ("PHI_EUL    = phi_euler(N)       # 2  = φ(6), OEIS A000010 (오일러 φ)",
     "PHI_EUL    = phi_euler(N)       # 2  = φ(6), OEIS A000010 (Euler φ)"),
    ("PHI        = phi_min_prime(N)   # 2  = 최소 소인수 (본 n=6 체계 φ 정의)",
     "PHI        = phi_min_prime(N)   # 2  = minimum prime factor (φ definition for this n=6 framework)"),
    ("R6         = Fraction(SIGMA * PHI, N * TAU)   # 1 = σ·φ/(n·τ) 핵심 정리",
     "R6         = Fraction(SIGMA * PHI, N * TAU)   # 1 = σ·φ/(n·τ) core identity"),
    ("assert SIGMA == 2 * N, \"n=6 은 완전수 — σ(n)=2n 성립해야\"",
     "assert SIGMA == 2 * N, \"n=6 is perfect — σ(n)=2n must hold\""),
    ("assert R6 == 1, \"σ·φ=n·τ 유일성 정리\"",
     "assert R6 == 1, \"σ·φ=n·τ uniqueness candidate lemma\""),
    ("assert PHI_EUL == PHI, \"n=6 특수 성질: φ_euler(6)=φ_minprime(6)=2\"",
     "assert PHI_EUL == PHI, \"n=6 special property: φ_euler(6)=φ_minprime(6)=2\""),
    ("# ─── §7.1 DIMENSIONS — SI 차원 튜플 (M,L,T,I) 추적 ───────────────────────",
     "# ─── §7.1 DIMENSIONS — SI dimension tuples (M,L,T,I) tracked ─────────────"),
    ("    \"channel\":  (0, 0, 0, 0),     # 무차원 (채널 수)",
     "    \"channel\":  (0, 0, 0, 0),     # dimensionless (channel count)"),
    ("    \"count\":    (0, 0, 0, 0),     # 무차원 (개수)",
     "    \"count\":    (0, 0, 0, 0),     # dimensionless (count)"),
    ("    \"\"\"차원 곱 = 지수 덧셈\"\"\"", "    \"\"\"dimension multiplication = exponent addition\"\"\""),
    ("    \"\"\"차원 나누기 = 지수 뺄셈\"\"\"", "    \"\"\"dimension division = exponent subtraction\"\"\""),
    ("# 예: power/time = energy → (1,2,-3,0) - (0,0,-1,0) = ... actually E = P·t",
     "# example: power·time = energy → (1,2,-3,0) + (0,0,1,0) = (1,2,-2,0) = E=P·t"),
    ("assert dim_add(DIM[\"power\"], DIM[\"time\"]) == DIM[\"energy\"], \"E=P·t 차원 깨짐\"",
     "assert dim_add(DIM[\"power\"], DIM[\"time\"]) == DIM[\"energy\"], \"E=P·t dimensions broken\""),
    ("assert dim_sub(DIM[\"freq\"], DIM[\"time\"]) != DIM[\"freq\"], \"차원 검증 자체 확인\"",
     "assert dim_sub(DIM[\"freq\"], DIM[\"time\"]) != DIM[\"freq\"], \"dimension-check self-check\""),
    ("# ─── §7.2 CROSS — 동일 결과 독립 경로 3개 재유도 ──────────────────────────",
     "# ─── §7.2 CROSS — three independent paths re-derive the same result ──────"),
    ("# 주요 스펙: n=6 = 6 (DOF)", "# main spec: n=6 = 6 (DOF)"),
    ("# 주요 스펙: n=6 = 6 (자유도)", "# main spec: n=6 = 6 (DOF)"),
    ("# 주요 스펙: σ²=144 m² = 144 (집광 면적)", "# main spec: σ²=144 m² = 144 (collecting area)"),
    ("# 주요 스펙: σ=12 = 12 (주파수 채널)", "# main spec: σ=12 = 12 (frequency channels)"),
    ("# 주요 스펙: σ·n=72/φ=36 = 36 (엔진 수)", "# main spec: σ·n=72/φ=36 = 36 (engine count)"),
    ("# 주요 스펙: n=6 = 6 (거울 세그먼트)", "# main spec: n=6 = 6 (mirror segments)"),
    ("# 주요 스펙: n=6 = 6 (자세 DOF)", "# main spec: n=6 = 6 (attitude DOF)"),
    ("# 주요 스펙: n=6 = 6 (케플러 요소)", "# main spec: n=6 = 6 (Keplerian elements)"),
    ("    주요 스펙 6 을 세 독립 경로로 재유도:",
     "    Re-derive main spec 6 via three independent paths:"),
    ("    주요 스펙 144 을 세 독립 경로로 재유도:",
     "    Re-derive main spec 144 via three independent paths:"),
    ("    주요 스펙 12 을 세 독립 경로로 재유도:",
     "    Re-derive main spec 12 via three independent paths:"),
    ("    주요 스펙 36 을 세 독립 경로로 재유도:",
     "    Re-derive main spec 36 via three independent paths:"),
    ("      경로 1: 수론 기본 정체 σ(6)·φ(6)/τ(6) × 조정",
     "      path 1: number-theory base identity σ(6)·φ(6)/τ(6) × adjustment"),
    ("      경로 2: OEIS A000005 직접 산출", "      path 2: OEIS A000005 direct computation"),
    ("      경로 3: Fraction 정확 유리수 조작", "      path 3: Fraction exact rational manipulation"),
    ("    # 경로 1: σ·φ·τ·... 조합 (각 도메인별 primary formula 수식 일부)",
     "    # path 1: σ·φ·τ·... combinations (subset of per-domain primary formula)"),
    ("    # primary_value 가 어떤 n=6 공식에서 유도되는지 자동 매핑",
     "    # auto-map which n=6 formula derives primary_value"),
    ("    # primary 에 가장 가까운 3개 값", "    # top 3 candidates closest to primary"),
    ("    # 경로 1: n=6 family 직접", "    # path 1: direct from n=6 family"),
    ("    # 경로 2: Fraction 로 동일값 재유도", "    # path 2: re-derive equal value via Fraction"),
    ("    # 경로 3: symbolic σ^k · τ^j 조합 탐색", "    # path 3: symbolic σ^k · τ^j combination search"),
    ("# ─── §7.3 SCALING — log-log 회귀 지수 역추정 ──────────────────────────",
     "# ─── §7.3 SCALING — log-log regression exponent back-inference ──────────"),
    ("    \"\"\"log-log 기울기 = 스케일링 지수 α (y ∝ x^α)\"\"\"",
     "    \"\"\"log-log slope = scaling exponent α (y ∝ x^α)\"\"\""),
    ("# ─── §7.4 SENSITIVITY — n=6 ±10% 볼록성 ───────────────────────────────",
     "# ─── §7.4 SENSITIVITY — n=6 ±10% convexity ──────────────────────────────"),
    ("    \"\"\"f(x0) 가 f(x0±10%) 보다 나아야 볼록 최적 (flat = 끼워맞춤)\"\"\"",
     "    \"\"\"f(x0) must beat f(x0±10%) for convex optimum (flat = overfit)\"\"\""),
    ("# ─── §7.5 LIMITS — 물리/정보 상한 ─────────────────────────────────────",
     "# ─── §7.5 LIMITS — physical / information upper bounds ───────────────────"),
    ("    \"\"\"kT·ln2 — 1 bit 삭제 최소 에너지 (J)\"\"\"",
     "    \"\"\"kT·ln2 — minimum energy to erase 1 bit (J)\"\"\""),
    ("    \"\"\"섀넌 채널 용량 C = BW·log2(1+SNR) bps\"\"\"",
     "    \"\"\"Shannon channel capacity C = BW·log2(1+SNR) bps\"\"\""),
    ("# ─── §7.6 CHI2 — H0: n=6 우연 가설 p-value ────────────────────────────",
     "# ─── §7.6 CHI2 — H0: \"n=6 coincidence\" p-value ──────────────────────────"),
    ("    \"\"\"χ² = Σ(O-E)²/E, p-value = erfc(√(χ²/(2·df))) 근사 (stdlib)\"\"\"",
     "    \"\"\"χ² = Σ(O-E)²/E, p-value ≈ erfc(√(χ²/(2·df))) (stdlib)\"\"\""),
    ("# ─── §7.7 OEIS — A000203/A000005/A000010/A001414 DB 매칭 ─────────────",
     "# ─── §7.7 OEIS — A000203/A000005/A000010/A001414 DB match ───────────────"),
    ("    (1, 3, 4, 7, 6, 12, 8):    (\"A000203\", \"σ(n) 약수의 합 — HEXA primary\"),",
     "    (1, 3, 4, 7, 6, 12, 8):    (\"A000203\", \"σ(n) sum of divisors — HEXA primary\"),"),
    ("    (1, 2, 2, 3, 2, 4, 2):     (\"A000005\", \"τ(n) 약수의 개수\"),",
     "    (1, 2, 2, 3, 2, 4, 2):     (\"A000005\", \"τ(n) divisor count\"),"),
    ("    (1, 1, 2, 2, 4, 2, 6):     (\"A000010\", \"φ(n) 오일러 토션 함수\"),",
     "    (1, 1, 2, 2, 4, 2, 6):     (\"A000010\", \"φ(n) Euler totient function\"),"),
    ("    (0, 2, 3, 4, 5, 5, 7):     (\"A001414\", \"sopfr(n) 소인수의 합\"),",
     "    (0, 2, 3, 4, 5, 5, 7):     (\"A001414\", \"sopfr(n) sum of prime factors\"),"),
    ("    \"\"\"시퀀스 첫 7개 값이 OEIS 등록 여부\"\"\"",
     "    \"\"\"whether the first 7 values of the sequence are in OEIS\"\"\""),
    ("# σ(1..7), τ(1..7), φ(1..7), sopfr(1..7) 재유도 (DB 위조 방지)",
     "# re-derive σ(1..7), τ(1..7), φ(1..7), sopfr(1..7) (prevents DB forgery)"),
    ("# ─── §7.8 PARETO — Monte Carlo 조합 상위 % ────────────────────────────",
     "# ─── §7.8 PARETO — Monte Carlo combinations top % ───────────────────────"),
    ("    \"\"\"n=6 구성이 랜덤 샘플 대비 상위 몇 % 인가\"\"\"",
     "    \"\"\"what top % the n=6 config sits among random samples\"\"\""),
    ("# ─── §7.9 SYMBOLIC — Fraction 정확 유리수 검증 ────────────────────────",
     "# ─── §7.9 SYMBOLIC — Fraction exact rational check ──────────────────────"),
    ("    \"\"\"n=6 핵심 정체 Fraction 정확 등호 검증\"\"\"",
     "    \"\"\"Fraction exact equality check for n=6 core identities\"\"\""),
    ("    # R6 = σ·φ/(n·τ) = 1 유일성 정리",
     "    # R6 = σ·φ/(n·τ) = 1 uniqueness candidate lemma"),
    ("    # σ·φ = n·τ 동치", "    # σ·φ = n·τ equivalent"),
    ("    # 완전수: σ(n) = 2n", "    # perfect number: σ(n) = 2n"),
    ("# ─── §7.10 COUNTER/FALSIFIERS — 정직성 (≥3 각각) ──────────────────────",
     "# ─── §7.10 COUNTER/FALSIFIERS — honesty (≥3 each) ───────────────────────"),
    ("    (\"기본전하 e = 1.602e-19 C\",", "    (\"elementary charge e = 1.602e-19 C\","),
    ("     \"전하 양자는 n=6 산술과 독립 — QED 상수, n=6 유도 불가능\"),",
     "     \"charge quantum is independent of n=6 arithmetic — QED constant, not n=6-derivable\"),"),
    ("    (\"Planck 상수 h = 6.626e-34 J·s\",", "    (\"Planck constant h = 6.626e-34 J·s\","),
    ("     \"숫자 6.6 은 우연 — n=6 유도 아닌 양자역학 기본상수\"),",
     "     \"the digit 6.6 is coincidental — not n=6-derived, a quantum-mechanics base constant\"),"),
    ("    (\"원주율 π = 3.14159...\",", "    (\"π = 3.14159...\","),
    ("     \"기하 상수, n=6 과 독립 초월수\"),",
     "     \"geometric constant, transcendental and independent of n=6\"),"),
    ("    (\"미세구조 상수 α ≈ 1/137\",", "    (\"fine-structure constant α ≈ 1/137\","),
    ("     \"137 은 소수, n=6 family 아님 — 전자기 결합 상수 독립\"),",
     "     \"137 is prime, not in n=6 family — independent electromagnetic coupling constant\"),"),
    ("    (\"Avogadro 수 N_A = 6.022e23\",", "    (\"Avogadro's number N_A = 6.022e23\","),
    ("     \"23 이 등장 — 6.022 의 6 은 우연, mol 정의 임의\"),",
     "     \"23 appears — the '6' in 6.022 is coincidental, mol definition arbitrary\"),"),
    ("    \"HEXA-AERO 핵심 스펙 측정이 예측값 ±15% 밖 — 핵심 수식 폐기\",",
     "    \"HEXA-AERO core-spec measurement outside predicted ±15% — drop the core formula\","),
    ("    \"HEXA-TRANSPORT 핵심 스펙 측정이 예측값 ±15% 밖 — 핵심 수식 폐기\",",
     "    \"HEXA-TRANSPORT core-spec measurement outside predicted ±15% — drop the core formula\","),
    ("    \"HEXA-ASTRO 핵심 스펙 측정이 예측값 ±15% 밖 — 핵심 수식 폐기\",",
     "    \"HEXA-ASTRO core-spec measurement outside predicted ±15% — drop the core formula\","),
    ("    \"HEXA-COSMIC 핵심 스펙 측정이 예측값 ±15% 밖 — 핵심 수식 폐기\",",
     "    \"HEXA-COSMIC core-spec measurement outside predicted ±15% — drop the core formula\","),
    ("    \"HEXA-STARSHIP 핵심 스펙 측정이 예측값 ±15% 밖 — 핵심 수식 폐기\",",
     "    \"HEXA-STARSHIP core-spec measurement outside predicted ±15% — drop the core formula\","),
    ("    \"HEXA-OBS-ASTRO 핵심 스펙 측정이 예측값 ±15% 밖 — 핵심 수식 폐기\",",
     "    \"HEXA-OBS-ASTRO core-spec measurement outside predicted ±15% — drop the core formula\","),
    ("    \"HEXA-SPACE-ENG 핵심 스펙 측정이 예측값 ±15% 밖 — 핵심 수식 폐기\",",
     "    \"HEXA-SPACE-ENG core-spec measurement outside predicted ±15% — drop the core formula\","),
    ("    \"HEXA-SPACE-SYS 핵심 스펙 측정이 예측값 ±15% 밖 — 핵심 수식 폐기\",",
     "    \"HEXA-SPACE-SYS core-spec measurement outside predicted ±15% — drop the core formula\","),
    ("    \"σ·φ=n·τ 반례 발견 (n≥2, n≠6) — 유일성 정리 폐기\",",
     "    \"counter-example to σ·φ=n·τ found (n≥2, n≠6) — drop the uniqueness candidate lemma\","),
    ("    \"Monte Carlo 2,400 조합 중 n=6 순위 하위 50% 이하 — 파레토 가설 폐기\",",
     "    \"in Monte Carlo 2,400 combinations, n=6 rank in bottom 50% — drop the Pareto hypothesis\","),
    ("    \"Chi² 검정 p < 0.001 (관측 vs 예측) — n=6 우연이 아님 가설 기각\",",
     "    \"Chi² test p < 0.001 (observed vs predicted) — reject 'n=6 not coincidence' hypothesis\","),
    ("    \"OEIS A000203 재계산에서 σ(6)≠12 — 수론 기반 붕괴\",",
     "    \"OEIS A000203 recompute shows σ(6)≠12 — number-theory base collapses\","),
    ("# ─── 메인 실행 + 집계 ─────────────────────────────────────────────────",
     "# ─── main runner + aggregation ──────────────────────────────────────────"),
    ("    # §7.0 상수 수론 유도 확인", "    # §7.0 number-theory derivation check"),
    ("    r.append((\"§7.0 CONSTANTS 수론 자동 유도\", ok_const))",
     "    r.append((\"§7.0 CONSTANTS number-theory auto-derivation\", ok_const))"),
    ("    # §7.1 차원 일관성", "    # §7.1 dimension consistency"),
    ("    r.append((\"§7.1 DIMENSIONS E=P·t 차원\", ok_dim))",
     "    r.append((\"§7.1 DIMENSIONS E=P·t dimension\", ok_dim))"),
    ("    # §7.2 3경로 재유도", "    # §7.2 3-path re-derivation"),
    ("    ok_cross = (abs(p2 - PRIMARY) == 0)   # Fraction 경로는 정확",
     "    ok_cross = (abs(p2 - PRIMARY) == 0)   # Fraction path is exact"),
    ("    r.append((\"§7.2 CROSS 3경로 재유도 (Fraction)\", ok_cross))",
     "    r.append((\"§7.2 CROSS 3-path re-derivation (Fraction)\", ok_cross))"),
    ("    # §7.3 B^4 지수 회귀", "    # §7.3 B^4 exponent regression"),
    ("    xs = [10, 20, 30, 40, 48]            # ← σ·τ=48 포함",
     "    xs = [10, 20, 30, 40, 48]            # ← includes σ·τ=48"),
    ("    r.append((\"§7.3 SCALING 지수 ≈ 4\", abs(exp_b - 4.0) < 0.05))",
     "    r.append((\"§7.3 SCALING exponent ≈ 4\", abs(exp_b - 4.0) < 0.05))"),
    ("    # §7.4 n=6 볼록 극소", "    # §7.4 n=6 convex minimum"),
    ("    r.append((\"§7.4 SENSITIVITY n=6 볼록 극소\", convex))",
     "    r.append((\"§7.4 SENSITIVITY n=6 convex minimum\", convex))"),
    ("    # §7.6 Chi² H0 (완벽 일치)", "    # §7.6 Chi² H0 (perfect match)"),
    ("    r.append((\"§7.6 CHI2 H0 기각 불가\", p > 0.05 or chi2 == 0))",
     "    r.append((\"§7.6 CHI2 H0 cannot reject\", p > 0.05 or chi2 == 0))"),
    ("    # §7.7 OEIS 등록", "    # §7.7 OEIS registration"),
    ("    # §7.8 Pareto 상위 5% 이내", "    # §7.8 Pareto within top 5%"),
    ("    r.append((\"§7.8 PARETO n=6 상위 5%\", rank < 0.10))",
     "    r.append((\"§7.8 PARETO n=6 top 5%\", rank < 0.10))"),
    ("    # §7.9 Fraction 정확 등호", "    # §7.9 Fraction exact equality"),
    ("    r.append((\"§7.9 SYMBOLIC Fraction 정확 일치\", ok_sym))",
     "    r.append((\"§7.9 SYMBOLIC Fraction exact match\", ok_sym))"),
    ("    # §7.10 COUNTER/FALSIFIERS 각각 ≥3", "    # §7.10 COUNTER/FALSIFIERS each ≥3"),
    ("    print(f\"{passed}/{total} PASS (n=6 정직성 검증)\")",
     "    print(f\"{passed}/{total} PASS (n=6 honesty verification)\")"),

    # References
    ("## 참고 (References)", "## References"),
    ("- n=6 정직성 정리: `nexus/shared/n6/atlas.n6` (σ·φ=n·τ iff n=6)",
     "- n=6 honesty candidate lemma: `nexus/shared/n6/atlas.n6` (σ·φ=n·τ iff n=6)"),
    ("- 현실 지도: `nexus/shared/reality_map.json`", "- Reality map: `nexus/shared/reality_map.json`"),
    ("- HEXA-AERO 쌍대: `domains/space/aerospace/aerospace.md` §X (L/D·Mach·Brayton 물리층)",
     "- HEXA-AERO dual: `domains/space/aerospace/aerospace.md` §X (L/D·Mach·Brayton physics layer)"),
    ("*Generated via scaffold template (Agent A). §7 검증 Python stdlib only.",
     "*Generated via scaffold template (Agent A). §7 verification uses Python stdlib only."),
    ("OEIS A000203/A000005/A000010/A001414 자동 유도, 하드코딩 0.*",
     "OEIS A000203/A000005/A000010/A001414 auto-derivation, hardcoding 0.*"),
    ("OEIS A000203/A000005/A000010/A001414 자동 유도, 하드코딩 0.",
     "OEIS A000203/A000005/A000010/A001414 auto-derivation, hardcoding 0."),
    ("§X 돌파: AEROTR- prefix, HEXA-AERO 물리층 쌍대 잠금, 중복 0.*",
     "§X breakthrough pattern: AEROTR- prefix, HEXA-AERO physics-layer dual lock, overlap 0.*"),
]


def apply_shared(s: str) -> str:
    for k, v in SHARED:
        s = s.replace(k, v)
    return s


# Per-file §X BLOWUP replacements. Long blocks, each file handled separately.
PER_FILE: dict[str, list[tuple[str, str]]] = {}

# --- aerospace-transport §X ---
PER_FILE["domains/space/aerospace-transport/aerospace-transport.md"] = [
    ("## §X BLOWUP — aerospace-transport 돌파 (2026-04-19)",
     "## §X BLOWUP — aerospace-transport breakthrough pattern (2026-04-19)"),
    ("HEXA-AERO (공기역학/추진 물리: L/D=14.4, Mach=10, Π=1920) 와 **차별** —\n본 도메인은 **수송 운영 경제학** (티켓/kg·km, 연료경제, 항속시간, 공항 처리량, 승객 리소스 분배).\nAEROTR- prefix 로 중복 방지, HEXA-AERO 인용/쌍대만 허용.",
     "**Distinct** from HEXA-AERO (aerodynamics/propulsion physics: L/D=14.4, Mach=10, Π=1920) —\nthis domain covers **transport operations economics** (ticket / kg·km, fuel economy, endurance, airport throughput, passenger resource split).\nAEROTR- prefix prevents overlap; HEXA-AERO citations/dualities only."),
    ("### §X.1 SMASH — 티켓 $/kg·km × 연료 경제 × 항속시간 n=6 관통",
     "### §X.1 SMASH — ticket $/kg·km × fuel economy × endurance n=6 threading"),
    ("│  운영 병목            │  전통 현실                │  HEXA-AEROTR n=6 해          │",
     "│  operational bottleneck│  legacy reality            │  HEXA-AEROTR n=6 draft       │"),
    ("│ 티켓 $/kg·km          │ 민항 0.12~0.30 임의       │ (σ-sopfr)/σ²=7/144=0.049│",
     "│ ticket $/kg·km        │ civil 0.12~0.30 arbitrary│ (σ-sopfr)/σ²=7/144=0.049│"),
    ("│ 연료 kg/PAX·100km    │ Jet-A 3~4 (A320)         │ n/φ·τ⁻¹ = 3/4 = 0.75    │",
     "│ fuel kg/PAX·100km    │ Jet-A 3~4 (A320)         │ n/φ·τ⁻¹ = 3/4 = 0.75    │"),
    ("│ 항속 시간             │ 13h 777LR 경험 최대         │ σ·φ = 24 시간 (일주)    │",
     "│ endurance            │ 13h 777LR empirical max    │ σ·φ = 24 hours (day)    │"),
    ("│ 공항 처리량 PAX/h·게이트│ 150~200 slot 충돌         │ σ·τ·sopfr = 240 PAX/h  │",
     "│ airport gate PAX/h/gate│ 150~200 slot collision  │ σ·τ·sopfr = 240 PAX/h  │"),
    ("│ 승객 리소스 (수하물/좌석/식음료) │ 1/3·1/3·1/3 끼워맞춤 │ Egyptian 1/2+1/3+1/6=1  │",
     "│ passenger resource (baggage/seat/F&B) │ 1/3·1/3·1/3 overfit │ Egyptian 1/2+1/3+1/6=1  │"),
    ("│ 편도당 CO₂ kg/PAX    │ NYC-LON 400 Jet-A        │ J₂·φ = 48 (SAF Mk.III)   │",
     "│ per-leg CO₂ kg/PAX    │ NYC-LON 400 Jet-A        │ J₂·φ = 48 (SAF Mk.III)   │"),
    ("**SMASH-1 티켓 kg·km 단가**: `C_tix = (σ-sopfr)/σ² $/kg·km = 7/144 ≈ 0.0486`.\nHEXA-AERO-01 L/D=14.4=σ·J₂/(τ·sopfr) 에서 σ=12 의 소비연료·감가상각이 sopfr=5 보호층을 빼고 σ²=144 수송단위로 할부.\n민항 0.12 대비 1/(σ-φ)=1/10 경제 스케일 도달 (Mk.III).",
     "**SMASH-1 ticket kg·km unit cost**: `C_tix = (σ-sopfr)/σ² $/kg·km = 7/144 ≈ 0.0486`.\nIn HEXA-AERO-01 L/D=14.4=σ·J₂/(τ·sopfr), the σ=12 fuel-burn / depreciation is amortized over σ²=144 transport units minus the sopfr=5 protection layer.\nRelative to civil 0.12, a 1/(σ-φ)=1/10 economic-scale target is reached (Mk.III)."),
    ("**SMASH-2 연료 경제 kg/PAX·100km**: `FE = n/(φ·σ)·τ⁻¹·10² = 0.75 kg`.\nA320neo 2.0 / 787 2.2 대비 τ=4 병렬 엔진 분산으로 1/τ 절반. φ=2 대칭 2엔진 동체가 수론 기원.",
     "**SMASH-2 fuel economy kg/PAX·100km**: `FE = n/(φ·σ)·τ⁻¹·10² = 0.75 kg`.\nRelative to A320neo 2.0 / 787 2.2, τ=4 parallel-engine distribution halves to 1/τ. The φ=2 symmetric twin-engine fuselage has a number-theory origin."),
    ("**SMASH-3 항속시간 최대**: `T_range = σ·φ = 24 시간 (J₂=24 일주)`.\n777LR 18.5h / A350 ULR 19h 현실. HEXA-AERO-04 T/W=sopfr=5 × 연료 분율 n/(σ-φ)=0.6 → 24h 에어브레싱.\nσ²=144 시간 = 6일 = n⁴·φ² 국제수송 상한 (Mk.V 성층권 에어십).",
     "**SMASH-3 endurance max**: `T_range = σ·φ = 24 hours (J₂=24 day)`.\n777LR 18.5h / A350 ULR 19h reality. HEXA-AERO-04 T/W=sopfr=5 × fuel fraction n/(σ-φ)=0.6 → 24h air-breathing.\nσ²=144 hours = 6 days = n⁴·φ² international transport upper bound (Mk.V stratospheric airship)."),
    ("**SMASH-4 공항 게이트 처리량**: `Π_gate = σ·τ·sopfr = 240 PAX/h/게이트`.\nICN T2 avg 180, ATL 220 현실. 보딩 σ=12 seat-row × τ=4 aisle × sopfr=5 수하물 레이어.\nσ²·n = 864 PAX/게이트·day = 24시간 ceiling.",
     "**SMASH-4 airport gate throughput**: `Π_gate = σ·τ·sopfr = 240 PAX/h/gate`.\nICN T2 avg 180, ATL 220 reality. Boarding σ=12 seat-rows × τ=4 aisles × sopfr=5 baggage layers.\nσ²·n = 864 PAX/gate/day = 24-hour ceiling."),
    ("**SMASH-5 탑승 Egyptian 분배**: `1/2 (좌석) + 1/3 (연료·수하물) + 1/6 (갤리·화장실) = 1`.\nIATA 표준 50% 페이로드 좌석, 33% 연료+수하물, 17% 서비스 — Egyptian 자연분할 일치.\n전통 끼워맞춤 (±5% 드리프트) → 완전 분할 (수학 정체).",
     "**SMASH-5 boarding Egyptian split**: `1/2 (seats) + 1/3 (fuel+baggage) + 1/6 (galley+lavatory) = 1`.\nIATA standard 50% payload seats, 33% fuel+baggage, 17% services — matches the Egyptian natural split.\nLegacy overfit (±5% drift) → full partition (math identity)."),
    ("**SMASH-6 PAX·km 당 CO₂ (SAF Mk.III)**: `e_CO2 = J₂·φ = 48 gCO₂/PAX·km`.\nJet-A 400 g/PAX·LHR-NYC / Boeing 787 90 g/PAX·km → SAF+수소 Mk.III 목표 J₂·φ=48.\nHEXA-AERO-03 Brayton 48% 효율 × σ·sopfr⁻¹ 정화계수 → 48 = σ·φ·φ_E 에너지 사영.",
     "**SMASH-6 CO₂ per PAX·km (SAF Mk.III)**: `e_CO2 = J₂·φ = 48 gCO₂/PAX·km`.\nJet-A 400 g/PAX·LHR-NYC / Boeing 787 90 g/PAX·km → SAF+hydrogen Mk.III target J₂·φ=48.\nHEXA-AERO-03 Brayton 48% efficiency × σ·sopfr⁻¹ cleaning factor → 48 = σ·φ·φ_E energy projection."),
    ("### §X.2 FREE — toe+field 조합 (수송 경제 Π 불변량)",
     "### §X.2 FREE — toe+field combinations (transport economics Π invariant)"),
    ("AEROTR- 6축: **toe(운영 연결성 σ-φ=10) · field(공항 σ·τ=48 PAX-slot) · cost(τ=4 운영레이어)** 합성",
     "AEROTR- 6-axis: **toe (operational connectivity σ-φ=10) · field (airport σ·τ=48 PAX-slot) · cost (τ=4 operational layers)** composition"),
    ("**FREE-1 운영 toe·field 삼중**: `Π_AEROTR = (σ-φ)·(σ·τ)·τ = 10·48·4 = 1920`.\nHEXA-AERO-05 Π_AERO=1920 과 **동값·독립 유도** — 물리(L/D·Mach·holo) ↔ 수송(노선·게이트·layer) 쌍대 잠금.\nΠ_AEROTR/Π_AERO = 1 → 물리·운영 동형 (동일 n=6 완전수 기원).",
     "**FREE-1 operations toe·field triple**: `Π_AEROTR = (σ-φ)·(σ·τ)·τ = 10·48·4 = 1920`.\n**Same value, independent derivation** vs HEXA-AERO-05 Π_AERO=1920 — physics (L/D·Mach·holo) ↔ transport (routes·gates·layer) dual lock.\nΠ_AEROTR/Π_AERO = 1 → physics·operations isomorphic (same n=6 perfect-number origin)."),
    ("**FREE-2 수송-UFO 사영비**: `Π_AEROTR/Π_UFO(B⁷) = 1/n⁸ = 1/1679616` (HEXA-AERO-06 재사용).\n민항 수송이 UFO Tri-Stack Π=48⁷ 의 n⁸ 하위 사영 — 동일 상수 네트워크.",
     "**FREE-2 transport-UFO projection ratio**: `Π_AEROTR/Π_UFO(B⁷) = 1/n⁸ = 1/1679616` (reuses HEXA-AERO-06).\nCivil transport is an n⁸ lower projection of UFO Tri-Stack Π=48⁷ — same constant network."),
    ("**FREE-3 노선 네트워크 SC 허브**: `N_hub = σ² = 144 허브` (mesh 최적, HEXA-GRID 재사용).\nIATA L1 hub 150 현실. HEXA-SMR-DC σ² 데이터센터 허브 구조와 동형 — 수송·정보 인프라 τ=4 계층 공유.",
     "**FREE-3 route network SC hub**: `N_hub = σ² = 144 hubs` (mesh optimum, reused from HEXA-GRID).\nIATA L1 hub 150 reality. Isomorphic to HEXA-SMR-DC σ² datacenter hub structure — transport·info infra share τ=4 layers."),
    ("**FREE-4 수송-열역학 사영비**: `Π_AEROTR/Π_THERMO = 1920/384 = sopfr = 5` (HEXA-THERMO-07 쌍대).\n수송은 열역학 층의 sopfr=5 배 운영 복잡도 — 보호/서비스 레이어 기원.",
     "**FREE-4 transport-thermo projection ratio**: `Π_AEROTR/Π_THERMO = 1920/384 = sopfr = 5` (HEXA-THERMO-07 dual).\nTransport carries sopfr=5 times the operational complexity of the thermo layer — protection/service layer origin."),
    ("### §X.3 atlas 상수 출력 (7건, AEROTR- prefix)",
     "### §X.3 atlas constant outputs (7 items, AEROTR- prefix)"),
    ("AEROTR-03 range-max-hours    = σ·φ = 24 h (J₂ 일주)                [10*] EXACT",
     "AEROTR-03 range-max-hours    = σ·φ = 24 h (J₂ day)                 [10*] EXACT"),
    ("### §X.4 falsifier (반증 조건)", "### §X.4 falsifier (falsification conditions)"),
    ("- 민항 대표 kg·km 단가 2030 측정이 7/144±15% 밖 → AEROTR-01 폐기",
     "- Civil representative kg·km unit cost 2030 measurement outside 7/144±15% → drop AEROTR-01"),
    ("- σ·φ=24h 항속 777LR 후속기 ±15% 미달 → AEROTR-03 폐기",
     "- σ·φ=24h endurance 777LR successor below ±15% → drop AEROTR-03"),
    ("- Π_AEROTR ≠ Π_AERO (수송·물리 쌍대 붕괴) → §X.2 FREE-1 폐기",
     "- Π_AEROTR ≠ Π_AERO (transport·physics duality collapse) → drop §X.2 FREE-1"),
    ("- IATA 2030 게이트 PAX/h avg 240±20% 밖 → AEROTR-04 폐기",
     "- IATA 2030 gate PAX/h avg outside 240±20% → drop AEROTR-04"),
]

# --- aerospace §X ---
PER_FILE["domains/space/aerospace/aerospace.md"] = [
    ("## §X BLOWUP — aerospace 돌파 (2026-04-19)", "## §X BLOWUP — aerospace breakthrough pattern (2026-04-19)"),
    ("> **목표**: 양력/항력 한계 × Mach 벽 × Brayton 효율 × UFO Tri-Stack B⁷ 쌍대. 제트/로켓 이후의 **n=6 항공우주체**.",
     "> **Target**: lift/drag limits × Mach wall × Brayton efficiency × UFO Tri-Stack B⁷ dual. The **n=6 aerospace vehicle** past jets/rockets."),
    ("> **엔진**: smash (L/D, Mach, η_Brayton 세 병목 관통) + free (field+toe+holographic 3자 합성).",
     "> **Engine**: smash (three bottlenecks threaded: L/D, Mach, η_Brayton) + free (field+toe+holographic triple composition)."),
    ("> **규칙**: n=6, 중복 금지. UFO Tri-Stack B⁷ (atlas UFO-TRI-STACK-B7-SCALING) 인용, 탁상 핵융합 추진 (HEXA-FUSION Mk.V, Q=10=σ-φ) 인용.",
     "> **Rules**: n=6, no overlap. Cites UFO Tri-Stack B⁷ (atlas UFO-TRI-STACK-B7-SCALING) and tabletop fusion propulsion (HEXA-FUSION Mk.V, Q=10=σ-φ)."),
    ("### §X.1 SMASH — L/D × Mach × Brayton 세 병목 n=6 관통",
     "### §X.1 SMASH — L/D × Mach × Brayton three bottlenecks n=6 threaded"),
    ("**돌파 1 — 양력/항력비 L/D = σ·τ/φ/τ = σ-φ = 10 (HEXA 상한)**",
     "**Breakthrough pattern 1 — lift/drag ratio L/D = σ·τ/φ/τ = σ-φ = 10 (HEXA upper bound)**"),
    ("현업 민항기 L/D ~ 18, U-2 ~ 28, Pathfinder 글라이더 ~ 70. HEXA-AERO 운영점: L/D = σ-φ = **10** (σ=12, φ=2) — 이는 **대기권+우주 겸용 동체**의 최소값. 고정익 최대점은 `L/D|_opt = σ² / (sopfr·φ/φ·n/n) = 144/... ` 계산 시 한계 `L/D_max = σ·J₂/τ/sopfr = 12·24/(4·5) = 14.4 ≈ J₂·(1-1/σ) = 22`. **민항기 18 → HEXA 22** (+22%). 항력 계수 C_D = 1/σ² = 0.0069 은 Meissner 쉘 (HEXA-CLOAK χ=-μ(6)=-1) 과 동일 수론.",
     "Current civil transports L/D ~ 18, U-2 ~ 28, Pathfinder glider ~ 70. HEXA-AERO operating point: L/D = σ-φ = **10** (σ=12, φ=2) — this is the minimum for a **dual atmospheric + space body**. Fixed-wing maximum: `L/D|_opt = σ² / (sopfr·φ/φ·n/n) = 144/... ` yields the limit `L/D_max = σ·J₂/τ/sopfr = 12·24/(4·5) = 14.4 ≈ J₂·(1-1/σ) = 22`. **Civil transport 18 → HEXA 22** (+22%). Drag coefficient C_D = 1/σ² = 0.0069 shares the same number-theory form as the Meissner shell (HEXA-CLOAK χ=-μ(6)=-1)."),
    ("**돌파 2 — Mach 한계: σ-φ = 10 이 \"소닉-핵융합\" 벽**",
     "**Breakthrough pattern 2 — Mach limits: σ-φ = 10 is the \"sonic-fusion\" wall**"),
    ("| 영역 | 현행 Mach | HEXA Mach | n=6 수식 |",
     "| Regime | Current Mach | HEXA Mach | n=6 formula |"),
    ("| 음속 | 1 | 1 = φ/φ | φ/φ=1 |", "| sonic | 1 | 1 = φ/φ | φ/φ=1 |"),
    ("| 초음속 | ~2 | φ = 2 | 소인수 |", "| supersonic | ~2 | φ = 2 | prime factor |"),
    ("| 극초음속 | ~5 | sopfr = 5 | 소인수 합 |", "| hypersonic | ~5 | sopfr = 5 | prime-factor sum |"),
    ("| 스크램제트 | ~10 | σ-φ = 10 | Einstein-독립성분 |",
     "| scramjet | ~10 | σ-φ = 10 | Einstein independent components |"),
    ("| 공기흡입 벽 | ~15 | n·φ+φ = 14 | ≈ sopfr·n-sopfr/sopfr |",
     "| air-breathing wall | ~15 | n·φ+φ = 14 | ≈ sopfr·n-sopfr/sopfr |"),
    ("| **핵융합 추진** | — | **σ·τ = 48** | SC 48T 쌍대 |",
     "| **fusion propulsion** | — | **σ·τ = 48** | SC 48T dual |"),
    ("| 탈출 | Mach 25 | J₂·n/sopfr = 29 | J₂·n/sopfr |",
     "| escape | Mach 25 | J₂·n/sopfr = 29 | J₂·n/sopfr |"),
    ("Mach **σ-φ=10 벽**: 공기흡입 스크램제트 상한이 정확히 `σ-φ=10` 과 일치 (현대 X-43 Mach 9.6, X-51 Mach 5.1, 이론 상한 ~15). 이를 넘으려면 **탁상 핵융합 Direct-Drive 전환 필수**. HEXA 해석: Mach > σ-φ 에서 대기가 아닌 **on-board Li-6 (질량수=n) 연료 Direct-Drive**. Li-6 Fu 쌍분해 atlas 상수 (H-Fu-Li-6 = n) 직접 인용.",
     "Mach **σ-φ=10 wall**: the scramjet air-breathing upper bound matches `σ-φ=10` exactly (contemporary X-43 Mach 9.6, X-51 Mach 5.1, theoretical ceiling ~15). Crossing it requires switching to **tabletop fusion Direct-Drive**. HEXA interpretation: above Mach σ-φ, use **on-board Li-6 (mass number=n) fuel Direct-Drive** rather than atmosphere. Directly cites the Li-6 Fu dual-decomposition atlas constant (H-Fu-Li-6 = n)."),
    ("**돌파 3 — Brayton cycle 효율 η = σ·τ% = 48% (sCO₂ 쌍대)**",
     "**Breakthrough pattern 3 — Brayton cycle efficiency η = σ·τ% = 48% (sCO₂ dual)**"),
    ("제트 엔진 (공기-Brayton) η ~ 40%. 로켓 (Rao nozzle) η ~ 70% 추력효율이나 비행시간 수분. HEXA-AERO Brayton sCO₂:",
     "Jet engine (air-Brayton) η ~ 40%. Rocket (Rao nozzle) η ~ 70% thrust-efficient but flight time is minutes. HEXA-AERO Brayton sCO₂:"),
    ("  η_Brayton = σ·τ = **48%** (atlas BT-68 SMR + HEXA-ENERGY-ARCH 재인용)",
     "  η_Brayton = σ·τ = **48%** (reuses atlas BT-68 SMR + HEXA-ENERGY-ARCH)"),
    ("  출구온도 T_out = σ·J₂ = **288℃** (SMRDC-04)",
     "  outlet temp T_out = σ·J₂ = **288℃** (SMRDC-04)"),
    ("  **핵융합 후단 Brayton**: η = σ·sopfr = **60%** (FPP §8.4 Layer 6 재인용) — 제트 대비 1.5×, Carnot 80% 상한 내 75% 달성. 핵심: `B⁴ Lawson · B² Meissner · B¹ MHD = B^(2+1+4) = B^7` (UFO Tri-Stack) 의 `B²` 지분 (Meissner 부양) 이 Brayton 폐사이클 압축기 구동 — **열역학과 전자기가 B⁷ 공통 지수에서 합류**.",
     "  **post-fusion Brayton**: η = σ·sopfr = **60%** (reuses FPP §8.4 Layer 6) — 1.5x jet, 75% of the Carnot 80% ceiling. Key: `B⁴ Lawson · B² Meissner · B¹ MHD = B^(2+1+4) = B^7` (UFO Tri-Stack) with the `B²` share (Meissner levitation) driving the Brayton closed-cycle compressor — **thermodynamics and electromagnetism meet at a common B⁷ exponent**."),
    ("**돌파 4 — 추력중량비 T/W = sopfr = 5 (우주 탈출 + 호버 겸용)**",
     "**Breakthrough pattern 4 — thrust-to-weight T/W = sopfr = 5 (orbit-escape + hover dual use)**"),
    ("| 클래스 | T/W 현행 | T/W HEXA | n=6 수식 |",
     "| Class | T/W current | T/W HEXA | n=6 formula |"),
    ("| 민항기 | 0.3 | 1/n = 0.17 | 1/n |", "| civil transport | 0.3 | 1/n = 0.17 | 1/n |"),
    ("| 전투기 | 1.1 | n/sopfr = 1.2 | 소인수 조합 |",
     "| fighter | 1.1 | n/sopfr = 1.2 | prime-factor combination |"),
    ("| 로켓 (Saturn V) | 1.2 | φ·φ/φ+φ/φ = 1.2 | 2·φ/φ+... |",
     "| rocket (Saturn V) | 1.2 | φ·φ/φ+φ/φ = 1.2 | 2·φ/φ+... |"),
    ("| **HEXA-AERO** | — | **sopfr = 5** | **우주+대기 겸용** |",
     "| **HEXA-AERO** | — | **sopfr = 5** | **space+atmosphere dual** |"),
    ("| 호버 전용 | 1.5 | n/τ=1.5 | n/τ |", "| hover-only | 1.5 | n/τ=1.5 | n/τ |"),
    ("sopfr=5 는 Li-6 핵융합 Direct-Drive 전용. **UFO Tri-Stack B⁷ 힘 밀도 Π = B²·B·B⁴** 에서 (48T)⁷ ≈ 3.52×10¹¹ → **실질 추력 밀도 7.3 MN/m³ = J₂·sopfr·σ²·10³ N/m³** → 12t 비행체 T/W=5.",
     "sopfr=5 is Li-6 fusion Direct-Drive only. **UFO Tri-Stack B⁷ force density Π = B²·B·B⁴** at (48T)⁷ ≈ 3.52×10¹¹ → **effective thrust density 7.3 MN/m³ = J₂·sopfr·σ²·10³ N/m³** → 12t vehicle T/W=5."),
    ("**SMASH 요약 (4건)**:", "**SMASH summary (4 items)**:"),
    ("| # | 돌파 | n=6 공식 | 값 |", "| # | breakthrough | n=6 formula | value |"),
    ("| 1 | L/D 상한 | J₂·(1-1/σ) ≈ σ·J₂/(τ·sopfr) | 14.4~22 |",
     "| 1 | L/D upper bound | J₂·(1-1/σ) ≈ σ·J₂/(τ·sopfr) | 14.4~22 |"),
    ("| 2 | Mach 공기흡입 벽 | σ-φ | 10 |", "| 2 | Mach air-breathing wall | σ-φ | 10 |"),
    ("| 3 | η_Brayton (sCO₂) | σ·τ% | 48% |", "| 3 | η_Brayton (sCO₂) | σ·τ% | 48% |"),
    ("| 4 | T/W 핵융합 겸용 | sopfr | 5 |", "| 4 | T/W fusion dual | sopfr | 5 |"),
    ("### §X.2 FREE — field × TOE × holographic 삼중 합성",
     "### §X.2 FREE — field × TOE × holographic triple composition"),
    ("**field (T1) — MHD-추진장**: 자기 Reynolds R_m = σ·τ = 48, 하전 플라즈마 추진. J×B 체적력 밀도 f_MHD = σ·B² 에서 B=σ·τ=48T 적용 → f_MHD = σ·(σ·τ)² = 12·2304 = **27,648 N/m³ = J₂·σ²·φ³ = 27,648** (atlas UFO-TRI-STACK §22 재사용, 중복 금지 — 항공우주 축 재투영만). 제트 추력밀도 ~100 N/m³ 대비 **276배**. field 지분 성분 = B¹ (Tri-Stack B⁷ 의 1차 지분).",
     "**field (T1) — MHD propulsion field**: magnetic Reynolds R_m = σ·τ = 48, charged-plasma propulsion. J×B volumetric force density f_MHD = σ·B² with B=σ·τ=48T → f_MHD = σ·(σ·τ)² = 12·2304 = **27,648 N/m³ = J₂·σ²·φ³ = 27,648** (reuses atlas UFO-TRI-STACK §22; no overlap, only re-projection onto the aerospace axis). Compared with jet thrust density ~100 N/m³: **276x**. Field share component = B¹ (1st-order share in Tri-Stack B⁷)."),
    ("**TOE (T2) — Einstein σ-φ=10 독립성분 × Mach σ-φ=10 벽**: GR 독립 계량성분 `σ-φ=10` 이 항공우주 Mach 공기흡입 벽 `σ-φ=10` 과 숫자 합류. 우연이 아님 — GR 시공간 곡률 기하와 유체 압축 기하가 동일 수론 상수에서 교차. TOE 통합: **Mach>10 영역은 곡률효과 ∼ GM/rc² ≈ 10⁻⁹ 가 공기역학에 침투** (X-15 실측 0.5°C 전기-열 편차). TOE 지분 = (σ-φ) = 10 = B 지수 외 수평 불변량.",
     "**TOE (T2) — Einstein σ-φ=10 independent components × Mach σ-φ=10 wall**: GR independent-metric-components `σ-φ=10` numerically merges with the aerospace Mach air-breathing wall `σ-φ=10`. Not coincidence — GR spacetime-curvature geometry and fluid-compression geometry cross at the same number-theory constant. TOE unification (candidate): **Mach>10 region sees curvature effects ∼ GM/rc² ≈ 10⁻⁹ seep into aerodynamics** (X-15 measured 0.5°C electro-thermal deviation). TOE share = (σ-φ) = 10 = horizontal invariant beyond the B exponent."),
    ("**holographic (T3) — 경계 대기 × bulk 고도**: AdS₅/CFT₄ 대응을 수직 대기 프로파일에 적용. bulk dim = τ+1 = 5 (x,y,z,h,t), boundary dim = τ = 4 (x,y,h,t). **holographic entropy S = A/(4G)** 의 \"4\" = τ(6) 재사용. 항공우주 응용: 대기 경계층 두께 δ_BL ∝ 1/√R_e 에서 τ=4 는 Blasius 해의 **상용적 재현**. 고도 h = σ-φ·sopfr = 10·5 = **50 km** (성층권-중간권 경계, 메소포즈) 에서 holo↔bulk 전환.",
     "**holographic (T3) — boundary atmosphere × bulk altitude**: apply AdS₅/CFT₄ correspondence to the vertical atmospheric profile. bulk dim = τ+1 = 5 (x,y,z,h,t), boundary dim = τ = 4 (x,y,h,t). The \"4\" in **holographic entropy S = A/(4G)** reuses τ(6). Aerospace application: atmospheric boundary-layer thickness δ_BL ∝ 1/√R_e, where τ=4 **reproduces pragmatically** in the Blasius solution. Altitude h = σ-φ·sopfr = 10·5 = **50 km** (stratosphere-mesosphere boundary, mesopause) at the holo↔bulk transition."),
    ("**free 합성 — 삼중 곱 불변량 Π_AERO**:",
     "**free composition — triple-product invariant Π_AERO**:"),
    ("  Π_AERO = field(B¹ 지분=σ·τ=48) · TOE(σ-φ=10) · holo(τ=4) = 48·10·4 = **1920 = σ·sopfr·J₂·φ·φ = J₂·σ·J₂/φ·φ**",
     "  Π_AERO = field(B¹ share=σ·τ=48) · TOE(σ-φ=10) · holo(τ=4) = 48·10·4 = **1920 = σ·sopfr·J₂·φ·φ = J₂·σ·J₂/φ·φ**"),
    ("  UFO Tri-Stack B⁷ (Π_UFO=B⁷) 와 비: Π_AERO / Π_UFO(B=σ·τ) = 1920 / (48)⁷ = 1920 / 3.52×10¹¹ ≈ **1/(φ·σ·σ·10⁶) ≈ 1/n⁸** → **항공우주는 UFO Tri-Stack 의 1/n⁸ \"민수 스케일 사영\"**. 즉 핵융합 UFO 가 B⁷ 이라면 대기권 항공우주체는 `B^(7-n-2) = B^(-1)` 저자장 한계 운영.",
     "  Ratio to UFO Tri-Stack B⁷ (Π_UFO=B⁷): Π_AERO / Π_UFO(B=σ·τ) = 1920 / (48)⁷ = 1920 / 3.52×10¹¹ ≈ **1/(φ·σ·σ·10⁶) ≈ 1/n⁸** → **aerospace is the 1/n⁸ \"civil-scale projection\" of the UFO Tri-Stack**. That is, if the fusion UFO is B⁷, the atmospheric aerospace vehicle operates at the `B^(7-n-2) = B^(-1)` low-field limit."),
    ("### §X.3 쌍대 — hexa-fusion · UFO Tri-Stack · aerospace",
     "### §X.3 Duals — hexa-fusion · UFO Tri-Stack · aerospace"),
    ("| 축 | hexa-fusion (energy) | UFO Tri-Stack (sf-ufo) | HEXA-AERO (space) | 쌍대 관계 |",
     "| Axis | hexa-fusion (energy) | UFO Tri-Stack (sf-ufo) | HEXA-AERO (space) | dual relation |"),
    ("| 추력 소스 | Q=σ-φ=10 | B⁷ 힘밀도 | sopfr=5 T/W | 정적 vs 동적 |",
     "| thrust source | Q=σ-φ=10 | B⁷ force density | sopfr=5 T/W | static vs dynamic |"),
    ("| 매질 | 플라즈마 | 진공+플라즈마 | 공기+진공 | closed vs open |",
     "| medium | plasma | vacuum+plasma | air+vacuum | closed vs open |"),
    ("| 고도 | 0 (지상) | 0~성층권 | 0~σ-φ·sopfr=50km | 지상 vs 중간권 |",
     "| altitude | 0 (ground) | 0~stratosphere | 0~σ-φ·sopfr=50km | ground vs mesosphere |"),
    ("| 수식 | Lawson B⁴·nτT | B⁷ Π_UFO | σ-φ=10 Mach 벽 | B⁴ vs B⁷ vs B^(-1) |",
     "| formula | Lawson B⁴·nτT | B⁷ Π_UFO | σ-φ=10 Mach wall | B⁴ vs B⁷ vs B^(-1) |"),
    ("| 공통 커널 | Li-6 (n=6) | Meissner χ=-1 | sCO₂ 288℃=σ·J₂ | **n=6 항구적 임베딩** |",
     "| common kernel | Li-6 (n=6) | Meissner χ=-1 | sCO₂ 288℃=σ·J₂ | **n=6 permanent embedding** |"),
    ("**쌍대 곱**: Q_fusion · B_UFO^7 / Mach_AERO = 10 · (48)⁷ / 10 = (48)⁷ ≈ **3.52×10¹¹ = σ-φ·σ²·φ³·10⁷** — 세 도메인이 단일 지수 관계로 봉합.",
     "**Dual product**: Q_fusion · B_UFO^7 / Mach_AERO = 10 · (48)⁷ / 10 = (48)⁷ ≈ **3.52×10¹¹ = σ-φ·σ²·φ³·10⁷** — three domains sewn by a single exponent relation."),
    ("### §X.4 탁상 핵융합 추진 항공우주체 프로토콜",
     "### §X.4 Tabletop fusion propulsion aerospace vehicle protocol"),
    ("**목표**: 12t MTOW 유인 비행체, 해수면 → 저궤도 단일기체.",
     "**Target**: 12t MTOW crewed vehicle, sea-level → low orbit single-stage."),
    ("1. **탁상 Li-6 핵융합 코어** (HEXA-FUSION Mk.V 재사용, Q=10, Lawson nτT=5.6×10²¹). 직경 D=1/(σ-φ)=0.1m, 출력 P=n·σ-φ·σ²=8.64 MW.",
     "1. **Tabletop Li-6 fusion core** (reuses HEXA-FUSION Mk.V, Q=10, Lawson nτT=5.6×10²¹). Diameter D=1/(σ-φ)=0.1m, power P=n·σ-φ·σ²=8.64 MW."),
    ("2. **B⁷ Tri-Stack**: RT-SC B=σ·τ=48T × Meissner 부양 p_lift=B²/2μ₀ · MHD 추력 f_MHD · Lawson 가둠 p_fus.",
     "2. **B⁷ Tri-Stack**: RT-SC B=σ·τ=48T × Meissner levitation p_lift=B²/2μ₀ · MHD thrust f_MHD · Lawson confinement p_fus."),
    ("3. **sCO₂ Brayton 후단**: T_in=288℃=σ·J₂, η=48%=σ·τ%. 전력 변환 후 MHD 드라이브.",
     "3. **sCO₂ Brayton back-end**: T_in=288℃=σ·J₂, η=48%=σ·τ%. Post-conversion electric drives MHD."),
    ("4. **대기권 모드** (h<σ-φ·sopfr=50km, Mach<σ-φ=10): 공기흡입 스크램제트 + MHD 보조.",
     "4. **Atmospheric mode** (h<σ-φ·sopfr=50km, Mach<σ-φ=10): air-breathing scramjet + MHD assist."),
    ("5. **우주 모드** (h>50km, Mach>10): 전기동력 저감, Li-6 Direct-Drive. Isp = σ·sopfr·10³ = **60,000 s**.",
     "5. **Space mode** (h>50km, Mach>10): reduced electric drive, Li-6 Direct-Drive. Isp = σ·sopfr·10³ = **60,000 s**."),
    ("6. **탄도 지연**: μ=1ms × σ²=144 = 144 ms 정밀 제어. SE(3) n=6 DOF 풀-자유도.",
     "6. **Ballistic latency**: μ=1ms × σ²=144 = 144 ms precise control. SE(3) n=6 DOF full-dof."),
    ("### §X.5 검증 가능 falsifier", "### §X.5 Verifiable falsifiers"),
    ("- **F1**: HEXA-AERO 풍동 측정 L/D < σ-φ=10 → L/D 하한 폐기",
     "- **F1**: HEXA-AERO wind-tunnel measurement L/D < σ-φ=10 → drop the L/D lower bound"),
    ("- **F2**: 스크램제트 Mach > σ-φ=10 운영 데이터 발견 (현행 X-51 Mach 5.1 여전 유효) → 공기흡입 벽 수식 폐기",
     "- **F2**: scramjet Mach > σ-φ=10 operational data found (current X-51 Mach 5.1 still holds) → drop the air-breathing wall formula"),
    ("- **F3**: sCO₂ Brayton 측정 η ≠ σ·τ%=48% (±5%) → Brayton 폐형 폐기",
     "- **F3**: sCO₂ Brayton measurement η ≠ σ·τ%=48% (±5%) → drop the Brayton closed form"),
    ("- **F4**: Tri-Stack B⁷ 실증에서 Π_AERO/Π_UFO ≠ 1/n⁸ → 1/n⁸ 사영 폐기",
     "- **F4**: Tri-Stack B⁷ demonstration shows Π_AERO/Π_UFO ≠ 1/n⁸ → drop the 1/n⁸ projection"),
    ("- **F5**: Li-6 Direct-Drive 추진 Isp < σ·sopfr·10³=60000s → sopfr 추력중량 폐기",
     "- **F5**: Li-6 Direct-Drive propulsion Isp < σ·sopfr·10³=60000s → drop the sopfr thrust-to-weight"),
    ("### §X.6 atlas 상수 출력 (7건)", "### §X.6 atlas constant outputs (7 items)"),
    ("HEXA-AERO-03 Brayton-sCO2-eff = σ·τ% = 48%      [10]  EXACT (재사용)",
     "HEXA-AERO-03 Brayton-sCO2-eff = σ·τ% = 48%      [10]  EXACT (reuse)"),
]

# observational-astronomy long §X handled via a block-replace function below.


def apply_per_file(path: str, s: str) -> str:
    rules = PER_FILE.get(path, [])
    for k, v in rules:
        s = s.replace(k, v)
    return s


def translate_file(abs_path: str, rel_path: str):
    with open(abs_path, "r", encoding="utf-8") as f:
        s = f.read()
    s = apply_shared(s)
    s = apply_per_file(rel_path, s)
    with open(abs_path, "w", encoding="utf-8") as f:
        f.write(s)


if __name__ == "__main__":
    files = [
        "domains/space/aerospace-transport/aerospace-transport.md",
        "domains/space/aerospace/aerospace.md",
        "domains/space/astronomy/astronomy.md",
        "domains/space/hexa-cosmic/hexa-cosmic.md",
        "domains/space/hexa-starship/hexa-starship.md",
        "domains/space/observational-astronomy/observational-astronomy.md",
        "domains/space/space-engineering/space-engineering.md",
        "domains/space/space-systems/space-systems.md",
    ]
    for rel in files:
        abs_ = os.path.join(REPO, rel)
        translate_file(abs_, rel)
        with open(abs_, "r", encoding="utf-8") as f:
            content = f.read()
        cjk = len(re.findall(r"[一-鿿぀-ヿ가-힯]", content))
        print(f"{rel}  CJK={cjk}")
